<?php
/**
 * {{MODEL_TITLE}} Model
 *
 * Generated by qscmf-backend skill
 * Framework: QSCMF (GyListModel base class)
 *
 * Manual TODO Checklist:
 * [ ] 1. Update namespace if not in Common\Model
 * [ ] 2. Configure $_validate rules for all fields
 * [ ] 3. Add $_auto rules for automatic field processing
 * [ ] 4. Implement custom business methods
 * [ ] 5. Configure caching strategy
 * [ ] 6. Add related model relationships
 * [ ] 7. Test all CRUD operations
 * [ ] 8. Add model events (after_insert, after_update, etc.)
 *
 * @package Common\Model
 */

namespace Common\Model;

use Gy_Library\GyListModel;
use Gy_Library\DBCont;
use Qscmf\Lib\Cache\QscmfCache;

/**
 * {{MODEL_TITLE}} Model
 *
 * Features:
 * - Automatic validation using $_validate
 * - Automatic field processing using $_auto
 * - Built-in CRUD methods with transactions
 * - Query caching with QscmfCache
 * - Soft delete support
 * - Status toggle methods (forbid/resume)
 * - List formatting with related data
 */
class {{MODEL_NAME}}Model extends GyListModel
{
    /**
     * Database table name
     *
     * @var string
     */
    protected $tableName = '{{TABLE_NAME}}';

    /**
     * Primary key field (default: 'id')
     *
     * @var string
     */
    protected $pk = 'id';

    /**
     * Field validation rules
     *
     * Validators available:
     * - require: Field must be present
     * - email: Valid email format
     * - url: Valid URL format
     * - currency: Valid currency format
     * - number: Must be numeric
     * - integer: Must be integer
     * - double: Must be double/float
     * - zip: Valid ZIP code
     * - phone: Valid phone number
     * - mobile: Valid mobile number
     * - idcard: Valid ID card number
     * - date: Valid date format
     * - time: Valid time format
     * - datetime: Valid datetime format
     * - unique: Field must be unique in table
     * - in: Value must be in specified array
     * - length: String length validation
     * - between: Numeric range validation
     * - regexp: Custom regex pattern
     * - callback: Custom validation function
     * - function: Custom validation function
     * - confirm: Must match another field (e.g., password_confirm)
     * - equal: Must equal specified value
     * - gt: Greater than
     * - egt: Greater than or equal to
     * - lt: Less than
     * - elt: Less than or equal to
     * - same: Same as another field
     *
     * Validation timing:
     * - self::MODEL_INSERT: Validate on insert only
     * - self::MODEL_UPDATE: Validate on update only
     * - self::MODEL_BOTH: Validate on both (default)
     *
     * @var array
     */
    protected $_validate = [
{{VALIDATE_RULES}}
        // ========== VALIDATION RULE EXAMPLES ==========

        // Required field (validate on both insert and update)
        // ['{{TABLE_NAME}}_name', 'require', '{{MODEL_TITLE}}名称不能为空', self::MODEL_BOTH],

        // Required only on insert (allow empty on update)
        // ['{{TABLE_NAME}}_code', 'require', '编码不能为空', self::MODEL_INSERT],

        // Unique validation
        // ['{{TABLE_NAME}}_code', 'unique', '编码已存在', self::MODEL_BOTH],

        // Email validation
        // ['email', 'email', '邮箱格式不正确', self::MODEL_BOTH],

        // URL validation
        // ['website', 'url', 'URL格式不正确', self::MODEL_BOTH],

        // Number validation with range
        // ['price', 'currency', '价格格式不正确', self::MODEL_BOTH],
        // ['price', 'between', '价格必须在0.01-999999之间', self::MODEL_BOTH, [0.01, 999999]],

        // Integer validation
        // ['sort', 'integer', '排序必须是整数', self::MODEL_BOTH],

        // String length validation (min,max)
        // ['{{TABLE_NAME}}_name', 'length', '名称长度必须在2-100之间', self::MODEL_BOTH, [2, 100]],

        // In array validation
        // ['status', 'in', '状态值不合法', self::MODEL_BOTH, [0, 1, 2]],

        // Phone number validation
        // ['telephone', 'phone', '电话号码格式不正确', self::MODEL_BOTH],

        // Mobile number validation
        // ['mobile', 'mobile', '手机号码格式不正确', self::MODEL_BOTH],

        // ID card validation
        // ['idcard', 'idcard', '身份证号码不正确', self::MODEL_BOTH],

        // Date validation
        // ['birth_date', 'date', '日期格式不正确', self::MODEL_BOTH],

        // Custom regex validation
        // ['{{TABLE_NAME}}_code', 'regexp', '编码只能包含字母、数字和下划线', self::MODEL_BOTH, '/^[a-zA-Z0-9_]+$/'],

        // Callback validation (custom function)
        // ['{{TABLE_NAME}}_name', 'callback', '名称已存在', self::MODEL_BOTH, function($name) {
        //     return !$this->where(['{{TABLE_NAME}}_name' => $name])->count();
        // }],

        // Function validation (calls model method)
        // ['custom_field', 'function', '自定义验证失败', self::MODEL_BOTH, 'checkCustomField'],

        // Confirm field validation (password confirmation)
        // ['password', 'confirm', '两次输入的密码不一致', self::MODEL_BOTH, 'password_confirm'],

        // Greater than validation
        // ['stock', 'gt', '库存必须大于0', self::MODEL_BOTH, 0],

        // Less than or equal validation
        // ['discount', 'elt', '折扣不能超过10', self::MODEL_BOTH, 10],
    ];

    /**
     * Automatic field processing
     *
     * Auto types:
     * - function: Call PHP function (time, date, md5, etc.)
     * - field: Copy value from another field
     * - callback: Custom callback function
     * - string: Fixed string value
     *
     * Processing timing:
     * - self::MODEL_INSERT: Process on insert only
     * - self::MODEL_UPDATE: Process on update only
     * - self::MODEL_BOTH: Process on both (default)
     *
     * Common functions:
     * - time: Current timestamp
     * - date: Current date (Y-m-d H:i:s)
     * - md5: MD5 hash
     * - htmlspecialchars: HTML special characters escape
     *
     * @var array
     */
    protected $_auto = [
        // ========== AUTO PROCESSING EXAMPLES ==========

        // Insert/Update: Set create_time on insert
        ['create_time', 'time', self::MODEL_INSERT, 'function'],

        // Insert/Update: Set update_time on both insert and update
        ['update_time', 'time', self::MODEL_BOTH, 'function'],

        // Insert: Hash password on create
        // ['password', 'md5', self::MODEL_INSERT, 'function'],

        // Insert: Set default status
        // ['status', 1, self::MODEL_INSERT, 'string'],

        // Update: Copy field value from another field
        // ['update_name', '{{TABLE_NAME}}_name', self::MODEL_UPDATE, 'field'],

        // Insert/Update: Custom callback function
        // ['custom_field', 'processCustomField', self::MODEL_BOTH, 'callback'],

        // Insert: Format data before save
        // ['data_json', 'formatJsonData', self::MODEL_INSERT, 'callback'],
    ];

    /**
     * Enable soft delete
     *
     * If true, delete() will set delete_time field instead of removing record
     * Requires delete_time field in table
     *
     * @var bool
     */
    protected $softDelete = false;

    /**
     * Query cache configuration
     *
     * Set to false to disable caching for all queries
     *
     * @var bool
     */
    protected $cacheEnabled = true;

    /**
     * Default cache TTL (seconds)
     *
     * @var int
     */
    protected $cacheTTL = 3600;

    /**
     * Parse search conditions for {{MODEL_TITLE}} list
     *
     * Commonly called from Controller::index()
     * Builds ThinkPHP where conditions from GET parameters
     *
     * Supported filter types:
     * - Keyword search (multi-field LIKE)
     * - Status filter (with 0 value support)
     * - Category/Foreign key filters
     * - Date range filters
     * - Number range filters
     * - Custom filters
     *
     * @param array $get_data GET parameters (I('get.'))
     * @param array &$map Reference to where conditions array (passed by reference)
     * @return void
     */
    public function parse{{MODEL_NAME}}Map(array $get_data = [], array &$map = []): void
    {
        // ========== KEYWORD SEARCH ==========
        if (isset($get_data['keyword']) && !qsEmpty($get_data['keyword'])) {
            $keyword = $get_data['keyword'];
            // Multi-field search (name OR code)
            $map['_complex'] = [
                '{{TABLE_NAME}}_name' => ['like', '%' . $keyword . '%'],
                '{{TABLE_NAME}}_code'  => ['like', '%' . $keyword . '%'],
                '_logic' => 'OR'
            ];
            // Alternative: Simple single field search
            // $map['{{TABLE_NAME}}_name'] = ['like', '%' . $keyword . '%'];
        }

        // ========== STATUS FILTER (supports 0 value) ==========
        if (isset($get_data['status']) && $get_data['status'] !== '') {
            $map['status'] = $get_data['status'];
        }

        // ========== CATEGORY/FILTER DROPDOWNS ==========
        if (isset($get_data['cate_id']) && !qsEmpty($get_data['cate_id'])) {
            $map['cate_id'] = $get_data['cate_id'];
        }

        // Custom foreign key filter
        // if (isset($get_data['type_id']) && !qsEmpty($get_data['type_id'])) {
        //     $map['type_id'] = $get_data['type_id'];
        // }

        // ========== DATE RANGE FILTER ==========
        if (isset($get_data['start_time']) && !qsEmpty($get_data['start_time'])) {
            $map['create_time'][] = ['egt', strtotime($get_data['start_time'])];
        }
        if (isset($get_data['end_time']) && !qsEmpty($get_data['end_time'])) {
            $map['create_time'][] = ['elt', strtotime($get_data['end_time'])];
        }

        // Alternative: Single date_range parameter (start,end)
        // if (isset($get_data['date_range']) && !qsEmpty($get_data['date_range'])) {
        //     [$start, $end] = explode(',', $get_data['date_range']);
        //     if ($start) $map['create_time'][] = ['egt', strtotime($start)];
        //     if ($end) $map['create_time'][] = ['elt', strtotime($end)];
        // }

        // ========== NUMBER RANGE FILTER ==========
        // Price range example
        // if (isset($get_data['price_min']) && !qsEmpty($get_data['price_min'])) {
        //     $map['price'][] = ['egt', $get_data['price_min']];
        // }
        // if (isset($get_data['price_max']) && !qsEmpty($get_data['price_max'])) {
        //     $map['price'][] = ['elt', $get_data['price_max']];
        // }

        // ========== CUSTOM FILTERS ==========
        // Example: Checkbox filter (multiple values)
        // if (isset($get_data['tags']) && !empty($get_data['tags'])) {
        //     $map['tags'] = ['like', '%' . $get_data['tags'] . '%'];
        // }

        // Example: Boolean filter
        // if (isset($get_data['is_featured'])) {
        //     $map['is_featured'] = $get_data['is_featured'] ? 1 : 0;
        // }
    }

    /**
     * Get {{MODEL_TITLE}} count by conditions
     *
     * @param array $map Query conditions
     * @return int Record count
     */
    public function get{{MODEL_NAME}}Count(array $map = []): int
    {
        return (int)$this->where($map)->count();
    }

    /**
     * Get {{MODEL_TITLE}} list with pagination
     *
     * @param array $map Query conditions
     * @param int|null $page Page number (null for no pagination)
     * @param int $per_page Items per page (default: 20)
     * @return array List of records
     */
    public function get{{MODEL_NAME}}List(array $map = [], ?int $page = null, int $per_page = 20): array
    {
        $model = $this->where($map);

        // Apply pagination if page is specified
        if (!is_null($page)) {
            $model->page($page, $per_page);
        }

        // Execute query
        $list = (array)$model->order('sort asc, id desc')->select();

        // Format list data (add related fields, format dates, etc.)
        $this->formatList($list);

        return $list;
    }

    /**
     * Get {{MODEL_TITLE}} detail by ID
     *
     * Uses caching to reduce database queries
     * Cache key: {{TABLE_NAME_SNAKE}}_detail_{id}
     *
     * @param int $id Record ID
     * @param bool $useCache Enable/disable cache (default: true)
     * @return array|null Record data or null if not found
     */
    public function get{{MODEL_NAME}}Detail(int $id, bool $useCache = true): ?array
    {
        // Use cache if enabled
        if ($useCache && $this->cacheEnabled) {
            $cache = new QscmfCache('{{TABLE_NAME_SNAKE}}_detail_' . $id, $this->cacheTTL);
            return $cache->remember(function() use ($id) {
                $data = $this->where(['id' => $id])->find();
                return $data ?: null;
            });
        }

        // Direct query without cache
        $data = $this->where(['id' => $id])->find();
        return $data ?: null;
    }

    /**
     * Add new {{MODEL_TITLE}} record
     *
     * Uses transaction for data safety
     * Returns new record ID on success
     *
     * @param array $data Record data
     * @return int New record ID (0 on failure)
     */
    public function add{{MODEL_NAME}}(array $data): int
    {
        $this->startTrans();
        try {
            // Create record (validates using $_validate)
            $id = $this->createAdd($data);
            if ($id === false) {
                E($this->getError());
            }

            // TODO: Add related data processing
            // Example: Process tags (many-to-many relationship)
            // if (isset($data['tags']) && is_array($data['tags'])) {
            //     D('{{MODEL_NAME}}TagRelation')->add{{MODEL_NAME}}Tags($id, $data['tags']);
            // }

            // Example: Process images
            // if (isset($data['gallery']) && is_array($data['gallery'])) {
            //     D('{{MODEL_NAME}}Image')->add{{MODEL_NAME}}Images($id, $data['gallery']);
            // }

            // Example: Initialize default values
            // $this->where(['id' => $id])->setField('sort', $id);

            $this->commit();
            return $id;

        } catch (\Exception $e) {
            $this->rollback();
            $this->error = $e->getMessage();
            return 0;
        }
    }

    /**
     * Update {{MODEL_TITLE}} record
     *
     * Uses transaction for data safety
     * Clears detail cache on success
     *
     * @param int $id Record ID
     * @param array $data Data to update
     * @return bool True on success, false on failure
     */
    public function update{{MODEL_NAME}}(int $id, array $data): bool
    {
        $this->startTrans();
        try {
            // Update record (validates using $_validate)
            $result = $this->where(['id' => $id])->save($data);
            if ($result === false) {
                E($this->getError());
            }

            // TODO: Update related data
            // Example: Sync tags (delete old, add new)
            // if (isset($data['tags']) && is_array($data['tags'])) {
            //     D('{{MODEL_NAME}}TagRelation')->sync{{MODEL_NAME}}Tags($id, $data['tags']);
            // }

            // Example: Update images
            // if (isset($data['gallery']) && is_array($data['gallery'])) {
            //     D('{{MODEL_NAME}}Image')->update{{MODEL_NAME}}Images($id, $data['gallery']);
            // }

            // Clear detail cache
            $cache = new QscmfCache('{{TABLE_NAME_SNAKE}}_detail_' . $id);
            $cache->clear();

            // Clear list cache (by tag)
            QscmfCache::clearByTag('{{TABLE_NAME_SNAKE}}_list');

            $this->commit();
            return true;

        } catch (\Exception $e) {
            $this->rollback();
            $this->error = $e->getMessage();
            return false;
        }
    }

    /**
     * Delete {{MODEL_TITLE}} record
     *
     * Supports hard delete and soft delete
     * Uses transaction for data safety
     * Clears related caches
     *
     * @param int $id Record ID
     * @return bool True on success, false on failure
     */
    public function delete{{MODEL_NAME}}(int $id): bool
    {
        $this->startTrans();
        try {
            // TODO: Check dependencies before delete
            // Example: Check if used in other tables
            // if (D('Order')->where(['{{TABLE_NAME}}_id' => $id])->count()) {
            //     E('该{{MODEL_TITLE}}正在使用中，无法删除');
            // }

            // TODO: Delete related data
            // Example: Delete tag relations
            // D('{{MODEL_NAME}}TagRelation')->where(['{{TABLE_NAME}}_id' => $id])->delete();

            // Example: Delete related images
            // D('{{MODEL_NAME}}Image')->where(['{{TABLE_NAME}}_id' => $id])->delete();

            // Soft delete (set delete_time)
            if ($this->softDelete) {
                $result = $this->where(['id' => $id])->setField('delete_time', time());
            } else {
                // Hard delete
                $result = $this->where(['id' => $id])->delete();
            }

            if ($result === false) {
                E($this->getError());
            }

            // Clear detail cache
            $cache = new QscmfCache('{{TABLE_NAME_SNAKE}}_detail_' . $id);
            $cache->clear();

            // Clear list cache
            QscmfCache::clearByTag('{{TABLE_NAME_SNAKE}}_list');

            $this->commit();
            return true;

        } catch (\Exception $e) {
            $this->rollback();
            $this->error = $e->getMessage();
            return false;
        }
    }

    /**
     * Batch delete {{MODEL_TITLE}} records
     *
     * @param array $ids Record IDs
     * @return array IDs of deleted records
     */
    public function batchDelete{{MODEL_NAME}}(array $ids): array
    {
        $deletedIds = [];

        foreach ($ids as $id) {
            if ($this->delete{{MODEL_NAME}}($id)) {
                $deletedIds[] = $id;
            }
        }

        return $deletedIds;
    }

    /**
     * Forbid (disable) {{MODEL_TITLE}} records
     *
     * Changes status from NORMAL_STATUS to DISABLE_STATUS
     * Only affects records with NORMAL_STATUS
     *
     * @param string|array $ids Single ID (string) or multiple IDs (array)
     * @return array IDs of affected records
     */
    public function forbid($ids): array
    {
        return $this->changeStatus($ids, DBCont::NORMAL_STATUS, DBCont::DISABLE_STATUS);
    }

    /**
     * Resume (enable) {{MODEL_TITLE}} records
     *
     * Changes status from DISABLE_STATUS to NORMAL_STATUS
     * Only affects records with DISABLE_STATUS
     *
     * @param string|array $ids Single ID (string) or multiple IDs (array)
     * @return array IDs of affected records
     */
    public function resume($ids): array
    {
        return $this->changeStatus($ids, DBCont::DISABLE_STATUS, DBCont::NORMAL_STATUS);
    }

    /**
     * Generic status change method
     *
     * Only changes records that match the source status
     * Prevents accidental status toggling
     *
     * @param string|array $ids Single ID or multiple IDs
     * @param int $from Source status (current status)
     * @param int $to Target status (new status)
     * @return array IDs of changed records
     */
    private function changeStatus($ids, int $from, int $to): array
    {
        // Convert to array if needed
        $id_array = is_array($ids) ? $ids : explode(',', $ids);
        $id_array = array_filter($id_array);
        $id_array = array_map('intval', $id_array);

        // Find records that match source status
        $need_change_ids = $this->where([
            'id' => ['IN', $id_array],
            'status' => $from
        ])->getField('id', true);

        if (empty($need_change_ids)) {
            return [];
        }

        // Update status
        $this->where(['id' => ['IN', $need_change_ids]])->setField('status', $to);

        // Clear cache
        QscmfCache::clearByTag('{{TABLE_NAME_SNAKE}}_list');

        return $need_change_ids;
    }

    /**
     * Format list data
     *
     * Adds related data, formats dates, processes images
     * Called automatically by get{{MODEL_NAME}}List()
     *
     * Common formatting tasks:
     * - Add related category names
     * - Format timestamps to readable dates
     * - Convert image IDs to URLs
     * - Add status text labels
     * - Compute derived fields
     *
     * @param array &$list Reference to list array (modified in place)
     * @return void
     */
    public function formatList(array &$list): void
    {
        if (empty($list)) {
            return;
        }

        // ========== BATCH LOAD RELATED DATA (avoid N+1 query problem) ==========

        // Get all category IDs
        $cate_ids = array_column($list, 'cate_id');
        $cate_ids = array_filter(array_unique($cate_ids));

        // Fetch categories in one query
        $cate_list = [];
        if (!empty($cate_ids)) {
            $cate_list = D('Category')
                ->where(['id' => ['IN', $cate_ids])
                ->getField('id,name', true);
        }

        // ========== FORMAT EACH RECORD ==========

        foreach ($list as &$item) {
            // Add category name
            $item['cate_name'] = $cate_list[$item['cate_id']]['name'] ?? '';

            // Add status text
            $item['status_text'] = DBCont::getStatusList()[$item['status']] ?? '未知';

            // Format image URL (if using attachment system)
            $item['cover_url'] = !empty($item['cover']) ? get_image_url($item['cover']) : '';

            // Format multiple images
            // $item['gallery_urls'] = [];
            // if (!empty($item['gallery'])) {
            //     $gallery_ids = explode(',', $item['gallery']);
            //     foreach ($gallery_ids as $img_id) {
            //         $item['gallery_urls'][] = get_image_url($img_id);
            //     }
            // }

            // Format timestamps
            $item['create_time_text'] = !empty($item['create_time'])
                ? date('Y-m-d H:i:s', $item['create_time'])
                : '';
            $item['update_time_text'] = !empty($item['update_time'])
                ? date('Y-m-d H:i:s', $item['update_time'])
                : '';

            // Format date
            $item['publish_date_text'] = !empty($item['publish_date'])
                ? date('Y-m-d', $item['publish_date'])
                : '';

            // TODO: Add custom formatting
            // Example: Calculate discount percentage
            // $item['discount_percent'] = $item['original_price'] > 0
            //     ? round(($item['original_price'] - $item['price']) / $item['original_price'] * 100, 2)
            //     : 0;

            // Example: Format price
            // $item['price_formatted'] = number_format($item['price'], 2);

            // Example: Boolean to text
            // $item['is_featured_text'] = $item['is_featured'] ? '是' : '否';
        }
    }

    /**
     * Get field options for dropdown
     *
     * Used in form selects and table columns
     * Returns array like [1 => 'Option 1', 2 => 'Option 2']
     *
     * @param string $field Field name
     * @param bool $withAll Include "All" option (default: false)
     * @return array Options array
     */
    public function getFieldOptions(string $field = 'id', bool $withAll = false): array
    {
        $options = $this->getField("{$field},{$this->pk}", true);

        if ($withAll) {
            $options = [0 => '全部'] + $options;
        }

        return $options;
    }

    // ========== CUSTOM BUSINESS METHODS ==========

    /**
     * Example: Increment view count
     *
     * @param int $id Record ID
     * @return bool
     */
    // public function incrementViews(int $id): bool
    // {
    //     return $this->where(['id' => $id])->setInc('view_count', 1);
    // }

    /**
     * Example: Decrement stock
     *
     * @param int $id Record ID
     * @param int $quantity Quantity to decrement
     * @return bool
     */
    // public function decrementStock(int $id, int $quantity = 1): bool
    // {
    //     return $this->where(['id' => $id])->setDec('stock', $quantity);
    // }

    /**
     * Example: Toggle featured status
     *
     * @param int $id Record ID
     * @return bool New featured status
     */
    // public function toggleFeatured(int $id): bool
    // {
    //     $record = $this->find($id);
    //     if (!$record) {
    //         return false;
    //     }
    //
    //     $newStatus = $record['is_featured'] ? 0 : 1;
    //     $this->where(['id' => $id])->setField('is_featured', $newStatus);
    //
    //     return $newStatus;
    // }

    /**
     * Example: Get featured items
     *
     * @param int $limit Limit count
     * @return array
     */
    // public function getFeatured(int $limit = 10): array
    // {
    //     $list = $this->where([
    //             'status' => DBCont::NORMAL_STATUS,
    //             'is_featured' => 1
    //         ])
    //         ->order('sort asc, id desc')
    //         ->limit($limit)
    //         ->select();
    //
    //     $this->formatList($list);
    //     return $list;
    // }

    /**
     * Example: Get related items
     *
     * @param int $id Record ID
     * @param int $limit Limit count
     * @return array
     */
    // public function getRelated(int $id, int $limit = 5): array
    // {
    //     $item = $this->find($id);
    //     if (!$item) {
    //         return [];
    //     }
    //
    //     $list = $this->where([
    //             'id' => ['NEQ', $id],
    //             'cate_id' => $item['cate_id'],
    //             'status' => DBCont::NORMAL_STATUS
    //         ])
    //         ->order('rand()')
    //         ->limit($limit)
    //         ->select();
    //
    //     $this->formatList($list);
    //     return $list;
    // }

    // ========== VALIDATION CALLBACKS ==========

    /**
     * Custom field validation example
     *
     * Called by $_validate callback validator
     *
     * @param mixed $value Field value
     * @return bool True if valid, false otherwise
     */
    // protected function checkCustomField($value): bool
    // {
    //     // Your custom validation logic here
    //     return true;
    // }

    // ========== AUTO CALLBACKS ==========

    /**
     * Custom field processing example
     *
     * Called by $_auto callback processor
     *
     * @param mixed $value Field value
     * @return mixed Processed value
     */
    // protected function processCustomField($value)
    // {
    //     // Your custom processing logic here
    //     return $value;
    // }

    // ========== MODEL EVENTS ==========

    /**
     * After insert event
     *
     * Called automatically after successful insert
     *
     * @param int $id New record ID
     * @param array $data Inserted data
     * @return void
     */
    // protected function afterInsert(int $id, array $data): void
    // {
    //     // TODO: Post-insert logic
    //     // Example: Log to activity log
    //     // D('ActivityLog')->record('{{MODEL_TITLE}}', 'create', $id, $data);
    // }

    /**
     * After update event
     *
     * Called automatically after successful update
     *
     * @param int $id Record ID
     * @param array $data Updated data
     * @return void
     */
    // protected function afterUpdate(int $id, array $data): void
    // {
    //     // TODO: Post-update logic
    //     // Example: Invalidate search index
    //     // D('SearchIndex')->update('{{TABLE_NAME}}', $id);
    // }

    /**
     * After delete event
     *
     * Called automatically after successful delete
     *
     * @param int $id Record ID
     * @return void
     */
    // protected function afterDelete(int $id): void
    // {
    //     // TODO: Post-delete logic
    //     // Example: Delete from search index
    //     // D('SearchIndex')->delete('{{TABLE_NAME}}', $id);
    // }
}
