<?php
/**
 * {{MODEL_TITLE}} API Controller
 *
 * Generated by qscmf-backend skill
 * Framework: QSCMF v14.x
 *
 * RESTful API endpoints:
 * - GET    /api/{{model}}         List records (with pagination)
 * - GET    /api/{{model}}/:id     Get single record
 * - POST   /api/{{model}}         Create record
 * - PUT    /api/{{model}}/:id     Update record
 * - DELETE /api/{{model}}/:id     Delete record
 *
 * Manual TODO Checklist:
 * [ ] 1. Add authentication/authorization
 * [ ] 2. Add input validation
 * [ ] 3. Add business logic
 * [ ] 4. Add rate limiting
 * [ ] 5. Write API tests
 *
 * @package Api\Controller
 */

namespace Api\Controller;

use Api\Controller\RestController;
use Gy_Library\DBCont;

class {{MODEL}}Controller extends RestController
{
    /**
     * Model name
     *
     * @var string
     */
    protected $modelName = '{{MODEL}}';

    /**
     * Allowed fields for output
     *
     * @var array
     */
    protected $allowFields = ['id', '{{TABLE_NAME}}_name', 'status', 'create_time', 'update_time'];

    /**
     * List records with pagination
     *
     * GET /api/{{model}}
     * Query params:
     * - page: Page number (default: 1)
     * - page_size: Items per page (default: 20, max: 100)
     * - status: Filter by status (optional)
     * - keyword: Search keyword (optional)
     *
     * @return void
     */
    public function index_get()
    {
        $page = I('get.page', 1, 'intval');
        $pageSize = min(I('get.page_size', 20, 'intval'), 100);

        $map = $this->buildQueryMap(I('get.'));

        $model = D($this->modelName);
        $list = $model->where($map)
            ->field($this->allowFields)
            ->order('id desc')
            ->page($page, $pageSize)
            ->select();

        $total = $model->where($map)->count();

        $this->response([
            'status' => true,
            'data' => $list,
            'meta' => [
                'total' => $total,
                'page' => $page,
                'page_size' => $pageSize,
                'total_pages' => ceil($total / $pageSize),
            ],
        ]);
    }

    /**
     * Get single record
     *
     * GET /api/{{model}}/:id
     *
     * @param int $id Record ID
     * @return void
     */
    public function detail_get($id = null)
    {
        $id = $id ?: I('get.id', 0, 'intval');

        if ($id <= 0) {
            $this->response(['status' => false, 'msg' => 'Invalid ID'], 400);
            return;
        }

        $data = D($this->modelName)->field($this->allowFields)->find($id);

        if (!$data) {
            $this->response(['status' => false, 'msg' => 'Record not found'], 404);
            return;
        }

        $this->response([
            'status' => true,
            'data' => $data,
        ]);
    }

    /**
     * Create record
     *
     * POST /api/{{model}}
     * Body: JSON data
     *
     * @return void
     */
    public function index_post()
    {
        $data = $this->getRequestData();

        // Validate input
        $validation = $this->validateCreate($data);
        if ($validation !== true) {
            $this->response(['status' => false, 'msg' => $validation], 422);
            return;
        }

        $model = D($this->modelName);
        $result = $model->createAdd($data);

        if ($result === false) {
            $this->response(['status' => false, 'msg' => $model->getError()], 422);
            return;
        }

        $this->response([
            'status' => true,
            'data' => ['id' => $result],
            'msg' => 'Created successfully',
        ], 201);
    }

    /**
     * Update record
     *
     * PUT /api/{{model}}/:id
     * Body: JSON data
     *
     * @param int $id Record ID
     * @return void
     */
    public function detail_put($id = null)
    {
        $id = $id ?: I('get.id', 0, 'intval');

        if ($id <= 0) {
            $this->response(['status' => false, 'msg' => 'Invalid ID'], 400);
            return;
        }

        $data = $this->getRequestData();
        $data['id'] = $id;

        $model = D($this->modelName);
        $result = $model->createSave($data);

        if ($result === false) {
            $this->response(['status' => false, 'msg' => $model->getError()], 422);
            return;
        }

        $this->response([
            'status' => true,
            'msg' => 'Updated successfully',
        ]);
    }

    /**
     * Delete record
     *
     * DELETE /api/{{model}}/:id
     *
     * @param int $id Record ID
     * @return void
     */
    public function detail_delete($id = null)
    {
        $id = $id ?: I('get.id', 0, 'intval');

        if ($id <= 0) {
            $this->response(['status' => false, 'msg' => 'Invalid ID'], 400);
            return;
        }

        $result = D($this->modelName)->delete($id);

        if ($result === false) {
            $this->response(['status' => false, 'msg' => 'Delete failed'], 500);
            return;
        }

        $this->response([
            'status' => true,
            'msg' => 'Deleted successfully',
        ]);
    }

    /**
     * Build query map from parameters
     *
     * @param array $params Query parameters
     * @return array
     */
    protected function buildQueryMap(array $params): array
    {
        $map = [];

        // Status filter
        if (isset($params['status']) && $params['status'] !== '') {
            $map['status'] = (int)$params['status'];
        } else {
            // Default: only active records
            $map['status'] = DBCont::NORMAL_STATUS;
        }

        // Keyword search
        if (!empty($params['keyword'])) {
            $map['{{TABLE_NAME}}_name'] = ['like', '%' . $params['keyword'] . '%'];
        }

        return $map;
    }

    /**
     * Validate create data
     *
     * @param array $data Input data
     * @return bool|string True if valid, error message otherwise
     */
    protected function validateCreate(array $data)
    {
        if (empty($data['{{TABLE_NAME}}_name'])) {
            return 'Name is required';
        }

        return true;
    }

    /**
     * Get request data (supports JSON body)
     *
     * @return array
     */
    protected function getRequestData(): array
    {
        $contentType = $_SERVER['CONTENT_TYPE'] ?? '';

        if (strpos($contentType, 'application/json') !== false) {
            $input = file_get_contents('php://input');
            return json_decode($input, true) ?: [];
        }

        return I('post.');
    }
}
