<?php
/**
 * {{MODEL_TITLE}} Model
 *
 * Generated by qscmf-backend skill
 * Framework: QSCMF v14.x
 *
 * Manual TODO Checklist:
 * [ ] 1. Add validation rules to $_validate
 * [ ] 2. Add auto-complete rules to $_auto
 * [ ] 3. Implement business logic methods
 * [ ] 4. Add cache methods if needed
 * [ ] 5. Configure relations if needed
 *
 * @package Common\Model
 */

namespace Common\Model;

use Gy_Library\GyListModel;
use Gy_Library\DBCont;

class {{MODEL}}Model extends GyListModel
{
    /**
     * Table name
     *
     * @var string
     */
    protected $tableName = '{{TABLE_NAME}}';

    /**
     * Primary key
     *
     * @var string
     */
    protected $pk = 'id';

    /**
     * Auto validate rules
     *
     * Format: [field, rule, message, validate_type, condition, callback_params]
     *
     * @var array
     */
    protected $_validate = [
        // ['field_name', 'require', '字段不能为空', self::MUST_VALIDATE],
        // ['field_name', 'unique', '该值已存在', self::VALUE_VALIDATE, 'callback', 'checkUnique'],
    ];

    /**
     * Auto complete rules
     *
     * Format: [field, rule, type, callback_params]
     *
     * @var array
     */
    protected $_auto = [
        ['create_time', 'time', self::MODEL_INSERT, 'function'],
        ['update_time', 'time', self::MODEL_BOTH, 'function'],
    ];

    /**
     * Get active records
     *
     * @return array
     */
    public function getActiveList(): array
    {
        return $this->where(['status' => DBCont::NORMAL_STATUS])
            ->order('sort asc, id desc')
            ->select();
    }

    /**
     * Get record by ID with cache
     *
     * @param int $id Record ID
     * @return array|null
     */
    public function getById(int $id): ?array
    {
        $cache_key = $this->tableName . '_detail_' . $id;
        $data = S($cache_key);

        if ($data === false) {
            $data = $this->find($id);
            if ($data) {
                S($cache_key, $data, 3600);
            }
        }

        return $data ?: null;
    }

    /**
     * Clear record cache
     *
     * @param int $id Record ID
     * @return void
     */
    public function clearCache(int $id): void
    {
        S($this->tableName . '_detail_' . $id, null);
        S($this->tableName . '_list', null);
    }

    /**
     * Check unique value
     *
     * @param string $value Field value
     * @param int $excludeId Exclude ID (for update)
     * @return bool
     */
    protected function checkUnique(string $value, int $excludeId = 0): bool
    {
        $map = [
            '{{TABLE_NAME}}_name' => $value,
        ];

        if ($excludeId > 0) {
            $map['id'] = ['NEQ', $excludeId];
        }

        return !$this->where($map)->count();
    }
}
