<?php
/**
 * {{MODEL_TITLE}} Admin Controller (v14 - AntdAdmin + React)
 *
 * Generated by qscmf-backend skill
 * Framework: QSCMF v14.x (ThinkPHP 3.2 + AntdAdmin)
 *
 * Manual TODO Checklist:
 * [ ] 1. Update namespace if not in Admin\Module
 * [ ] 2. Configure AntdAdmin column types in tableContainer()
 * [ ] 3. Add validation rules to Model $_validate
 * [ ] 4. Implement save() business logic
 * [ ] 5. Add delete() dependency checks
 * [ ] 6. Configure admin menu permissions
 * [ ] 7. Test all CRUD operations in browser
 * [ ] 8. Configure inline editing if needed
 * [ ] 9. Add custom renderers for complex columns
 *
 * @package Admin\Controller
 */

namespace Admin\Controller;
use Admin\Controller\QsListController;
use Gy_Library\Components\TableContainer;
use Gy_Library\Components\FormContainer;

/**
 * {{MODEL_TITLE}} Controller
 *
 * Features:
 * - AntdAdmin Table component (React-based UI)
 * - Inline editing support
 * - Advanced search with multiple filter types
 * - Batch operations with progress feedback
 * - Custom React component renderers
 * - Drag-and-drop file uploads
 * - Rich text editor integration
 */
class {{MODEL}}Controller extends QsListController
{
    /**
     * Model name (auto-instantiated as D('{{MODEL_NAME}}'))
     *
     * @var string
     */
    protected $modelName = '{{MODEL_NAME}}';

    /**
     * Table name (optional, defaults to {{TABLE_NAME}})
     *
     * @var string
     */
    protected $tableName = '{{TABLE_NAME}}';

    /**
     * Primary key field (default: 'id')
     *
     * @var string
     */
    protected $pk = 'id';

    /**
     * Enable soft delete (if table has delete_time field)
     *
     * @var bool
     */
    protected $softDelete = false;

    /**
     * List page - Main CRUD interface
     *
     * Displays AntdAdmin Table with:
     * - Search form (collapsible filters)
     * - Sortable columns
     * - Pagination
     * - Batch operations
     * - Row actions
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/index
     * Method: GET
     *
     * @return void
     */
    public function index()
    {
        // Step 1: Build search conditions from GET/POST
        $map = $this->buildSearchMap(I('get.'));

        // Step 2: Create TableContainer
        $container = new TableContainer($this);

        // Step 3: Configure table columns
        $this->tableContainer($container);

        // Step 4: Configure search form
        $container->setSearchForm($this->searchContainer($container));

        // Step 5: Set data source
        $model = D('{{MODEL_NAME}}')->where($map);
        $container->setData($model);

        // Step 6: Configure batch actions
        $this->batchActions($container);

        // Step 7: Display
        $this->display($container);
    }

    /**
     * Add new record form
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/add
     * Method: GET
     *
     * @return void
     */
    public function add()
    {
        $form = new FormContainer($this);
        $this->formContainer($form);
        $this->display($form);
    }

    /**
     * Edit existing record
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/edit
     * Method: GET
     * Query: id={record_id}
     *
     * @return void
     */
    public function edit()
    {
        $id = I('get.id', 0, 'intval');
        $data = D('{{MODEL_NAME}}')->find($id);

        if (!$data) {
            $this->error('记录不存在');
        }

        $form = new FormContainer($this);
        $this->formContainer($form);
        $form->setData($data);
        $this->display($form);
    }

    /**
     * Save record (create or update)
     *
     * Handles both create and update operations
     * Validates data and processes uploads
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/save
     * Method: POST
     *
     * @return void Redirects to index() or shows error
     */
    public function save()
    {
        // Get POST data
        $data = I('post.');

        // Validate required fields
        if (empty($data['{{TABLE_NAME}}_name'])) {
            $this->error('{{MODEL_TITLE}}名称不能为空');
        }

        // Start transaction
        D('{{MODEL_NAME}}')->startTrans();
        try {
            // TODO: Add your business logic here
            // Example: Process tags
            // if (isset($data['tags']) && is_array($data['tags'])) {
            //     $data['tags'] = implode(',', $data['tags']);
            // }

            // Example: Process rich text content
            // if (isset($data['content'])) {
            //     $data['content'] = clean_html($data['content']);
            // }

            // Example: Process images
            // if (isset($data['cover']) && is_numeric($data['cover'])) {
            //     $image_info = D('Attachment')->find($data['cover']);
            //     $data['cover_url'] = $image_info['url'];
            // }

            // Call parent save (validates using Model $_validate)
            $result = parent::save($data);

            if ($result === false) {
                E(D('{{MODEL_NAME}}')->getError());
            }

            D('{{MODEL_NAME}}')->commit();

            // TODO: Clear related caches
            // $this->clearCache();

            // TODO: Log action
            // D('AdminLog')->record($this->uid, '{{MODEL_TITLE}}', 'save', $data);

            $this->success('保存成功', U('index'));

        } catch (\Exception $e) {
            D('{{MODEL_NAME}}')->rollback();
            $this->error($e->getMessage());
        }
    }

    /**
     * Delete record
     *
     * Supports single and batch deletion
     * Checks dependencies before deletion
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/delete
     * Method: POST
     * Body: ids={comma_separated_ids}
     *
     * @return void
     */
    public function delete()
    {
        $ids = I('post.ids');
        if (empty($ids)) {
            $this->error('请选择要删除的记录');
        }

        $id_array = is_array($ids) ? $ids : explode(',', $ids);
        $id_array = array_map('intval', $id_array);

        // TODO: Add dependency checks
        // Example: Check if used in other tables
        // foreach ($id_array as $id) {
        //     $count = D('OtherTable')->where(['{{TABLE_NAME}}_id' => $id])->count();
        //     if ($count > 0) {
        //         $this->error('该{{MODEL_TITLE}}正在使用中，无法删除');
        //     }
        // }

        // TODO: If using soft delete
        // D('{{MODEL_NAME}}')->where(['id' => ['IN', $id_array]])->setField('delete_time', time());
        // $this->success('删除成功');

        // Hard delete (default)
        $result = D('{{MODEL_NAME}}')->where(['id' => ['IN', $id_array]])->delete();

        if ($result === false) {
            $this->error('删除失败');
        }

        // TODO: Clear cache
        // $this->clearCache();

        $this->success('删除成功');
    }

    /**
     * Inline edit handler
     *
     * Called when user edits a cell directly in table
     * Triggered by AntdAdmin Table editable() feature
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/inlineEdit
     * Method: POST
     * Body: {id: int, field: string, value: mixed}
     *
     * @return void
     */
    public function inlineEdit()
    {
        $id = I('post.id', 0, 'intval');
        $field = I('post.field', '', 'trim');
        $value = I('post.value');

        if (!$id || !$field) {
            $this->error('参数错误');
        }

        // Validate field is editable
        $editableFields = ['sort', 'status', 'title']; // TODO: Add your editable fields
        if (!in_array($field, $editableFields)) {
            $this->error('该字段不支持内联编辑');
        }

        // Update
        $result = D('{{MODEL_NAME}}')->where(['id' => $id])->setField($field, $value);

        if ($result === false) {
            $this->error('更新失败');
        }

        $this->success('更新成功');
    }

    /**
     * Build search conditions from GET parameters
     *
     * Supports:
     * - Multi-field keyword search
     * - Exact match filters
     * - Range filters (date, number)
     * - Status filters
     *
     * @param array $search GET parameters
     * @return array ThinkPHP where conditions
     */
    protected function buildSearchMap(array $search): array
    {
        $map = [];

        // Multi-field keyword search
        if (!empty($search['keyword'])) {
            $map['_complex'] = [
                '{{TABLE_NAME}}_name' => ['like', '%' . $search['keyword'] . '%'],
                '{{TABLE_NAME}}_code'  => ['like', '%' . $search['keyword'] . '%'],
                '_logic' => 'OR'
            ];
        }

        // Status filter (supports 0 value)
        if (isset($search['status']) && $search['status'] !== '') {
            $map['status'] = $search['status'];
        }

        // Category filter
        if (!empty($search['cate_id'])) {
            $map['cate_id'] = $search['cate_id'];
        }

        // Date range filter
        if (!empty($search['date_range'])) {
            [$start, $end] = explode(',', $search['date_range']);
            if ($start) $map['create_time'][] = ['egt', strtotime($start)];
            if ($end) $map['create_time'][] = ['elt', strtotime($end)];
        }

        // Price range filter
        if (!empty($search['price_range'])) {
            [$min, $max] = explode(',', $search['price_range']);
            if ($min) $map['price'][] = ['egt', $min];
            if ($max) $map['price'][] = ['elt', $max];
        }

        return $map;
    }

    /**
     * Configure table columns (v14 AntdAdmin)
     *
     * Available column methods:
     * - text($field, $title): Text column
     * - select($field, $title): Select dropdown display
     * - date($field, $title): Date display
     * - image($field, $title): Image display
     * - action(): Action buttons column
     * - custom($field, $title): Custom renderer
     *
     * Configuration methods:
     * - setSearch($enable): Enable search
     * - setSearchType($type): Set search type (like, exact, between)
     * - setSortable($enable): Enable sorting
     * - setWidth($width): Set column width
     * - setEllipsis($enable): Enable text ellipsis
     * - setShowCondition($condition): Conditional display
     * - setValueEnum($options): Set value mappings
     * - setRenderer($component): Set custom React renderer
     * - editable($options): Enable inline editing
     * - setBadge($colors): Set badge colors
     *
     * @param TableContainer $container
     * @return void
     */
    protected function tableContainer(TableContainer $container): void
    {
{{TABLE_COLUMNS}}
        // ========== COMMON COLUMN EXAMPLES ==========

        // ID column (hidden, sortable)
        // $container->text('id', 'ID')
        //     ->setSortable(true)
        //     ->setWidth(80)
        //     ->setShowCondition(['admin']); // Only show to admins

        // Text column with search
        // $container->text('{{TABLE_NAME}}_name', '名称')
        //     ->setSearch(true)
        //     ->setSearchType('like')
        //     ->setSearchPlaceholder('输入名称')
        //     ->setSortable(true)
        //     ->setEllipsis(true)
        //     ->setWidth(200);

        // Code column (exact search)
        // $container->text('{{TABLE_NAME}}_code', '编码')
        //     ->setSearch(true)
        //     ->setSearchType('exact')
        //     ->setSortable(true);

        // Status column with badges
        // $container->select('status', '状态')
        //     ->setValueEnum([
        //         1 => '启用',
        //         0 => '禁用',
        //         2 => '审核中'
        //     ])
        //     ->setSearch(true)
        //     ->setSearchType('exact')
        //     ->setBadge([
        //         1 => 'success', // Green
        //         0 => 'default', // Gray
        //         2 => 'processing' // Blue
        //     ]);

        // Category column (display name instead of ID)
        // $container->select('cate_id', '分类')
        //     ->setValueEnum(D('Category')->getFieldOptions())
        //     ->setSearch(true);

        // Price column (sortable, range search)
        // $container->text('price', '价格')
        //     ->setSortable(true)
        //     ->setSearch(true)
        //     ->setSearchType('between');

        // Date column
        // $container->date('create_time', '创建时间')
        //     ->setFormat('Y-m-d H:i:s')
        //     ->setSearch(true)
        //     ->setSearchType('between');

        // Image column
        // $container->image('cover', '封面')
        //     ->setWidth(100)
        //     ->setHeight(60);

        // Multiple images
        // $container->image('images', '图片集')
        //     ->setMultiple(true)
        //     ->setWidth(150);

        // Custom renderer (React component)
        // $container->custom('custom_field', '自定义')
        //     ->setRenderer('CustomRenderer')
        //     ->setRendererProps([
        //         'prop1' => 'value1',
        //         'prop2' => 'value2'
        //     ]);

        // Inline editable field
        // $container->text('sort', '排序')
        //     ->setWidth(100)
        //     ->editable([
        //         'type' => 'number',
        //         'min' => 0,
        //         'max' => 9999
        //     ]);

        // Complex display (custom function)
        // $container->text('full_info', '完整信息')
        //     ->setRenderer(function($row) {
        //         return $row['name'] . ' (' . $row['code'] . ')';
        //     });

        // ========== ACTION COLUMN (must be last) ==========

        // Action buttons (edit, delete, custom)
        $container->action('操作', [
            [
                'type' => 'edit',
                'title' => '编辑',
                'url' => U('edit', ['id' => '@id@'])
            ],
            [
                'type' => 'delete',
                'title' => '删除',
                'confirm' => '确定要删除该记录吗？'
            ],
            [
                'type' => 'custom',
                'title' => '查看',
                'url' => U('detail', ['id' => '@id@']),
                'icon' => 'eye',
                'ajax' => false
            ]
        ]);
    }

    /**
     * Configure search form
     *
     * Search field types:
     * - text(): Text input (default search type: like)
     * - select(): Dropdown (search type: exact)
     * - date(): Date picker
     * - time(): Time picker
     * - datetime(): DateTime picker
     * - number(): Number input
     *
     * @param TableContainer $container
     * @return \Gy_Library\Components\FormContainer
     */
    protected function searchContainer(TableContainer $container)
    {
        $form = new \Gy_Library\Components\FormContainer($container);

{{SEARCH_ITEMS}}
        // ========== SEARCH FIELD EXAMPLES ==========

        // Keyword search
        // $form->text('keyword', '关键词')
        //     ->setPlaceholder('输入名称或编码');

        // Status filter
        // $form->select('status', '状态')
        //     ->setOptions([
        //         '' => '全部',
        //         1 => '启用',
        //         0 => '禁用'
        //     ]);

        // Category filter
        // $form->select('cate_id', '分类')
        //     ->setOptions(D('Category')->getFieldOptions())
        //     ->setPlaceholder('选择分类');

        // Date range
        // $form->date('date_range', '创建时间')
        //     ->setRange(true)
        //     ->setFormat('Y-m-d');

        // Number range
        // $form->number('price_range', '价格范围')
        //     ->setRange(true);

        // DateTime range
        // $form->datetime('datetime_range', '时间范围')
        //     ->setRange(true)
        //     ->setFormat('Y-m-d H:i:s');

        return $form;
    }

    /**
     * Configure form fields for add/edit
     *
     * Form field types:
     * - text(): Single line text
     * - textarea(): Multi-line text
     * - number(): Number input
     * - select(): Dropdown
     * - radio(): Radio buttons
     * - checkbox(): Checkboxes
     * - date(): Date picker
     * - datetime(): DateTime picker
     * - time(): Time picker
     * - image(): Single image upload
     * - images(): Multiple image upload
     * - file(): File upload
     * - files(): Multiple file upload
     * - richText(): Rich text editor
     * - district(): District selector (province/city/area)
     * - password(): Password input
     * - url(): URL input
     * - email(): Email input
     * - phone(): Phone number input
     *
     * Validation methods:
     * - addRule($validator, $message, $condition): Add validation rule
     * - setRequired($message): Set required field
     *
     * @param FormContainer $form
     * @return void
     */
    protected function formContainer(FormContainer $form): void
    {
{{FORM_ITEMS}}
        // ========== FORM FIELD EXAMPLES ==========

        // Text input (required)
        // $form->text('{{TABLE_NAME}}_name', '名称')
        //     ->setRequired('请输入{{MODEL_TITLE}}名称')
        //     ->setPlaceholder('请输入名称')
        //     ->setFormItemWidth('lg');

        // Code input (unique validation)
        // $form->text('{{TABLE_NAME}}_code', '编码')
        //     ->setRequired('请输入编码')
        //     ->addRule('unique', '编码已存在', function($value) {
        //         return !D('{{MODEL_NAME}}')->where([
        //             '{{TABLE_NAME}}_code' => $value,
        //             'id' => ['NEQ', I('get.id', 0)]
        //         ])->count();
        //     });

        // Textarea
        // $form->textarea('description', '描述')
        //     ->setPlaceholder('请输入描述')
        //     ->setRows(4);

        // Rich text editor
        // $form->richText('content', '内容')
        //     ->setHeight(400)
        //     ->setUploadUrl(U('upload/ueditor'));

        // Select dropdown
        // $form->select('cate_id', '分类')
        //     ->setOptions(D('Category')->getFieldOptions())
        //     ->setRequired('请选择分类')
        //     ->setPlaceholder('选择分类');

        // Radio buttons
        // $form->radio('status', '状态')
        //     ->setOptions([
        //         1 => '启用',
        //         0 => '禁用'
        //     ])
        //     ->setDefault(1);

        // Checkboxes (multiple)
        // $form->checkbox('tags', '标签')
        //     ->setOptions([
        //         'tag1' => '标签1',
        //         'tag2' => '标签2',
        //         'tag3' => '标签3'
        //     ]);

        // Date picker
        // $form->date('publish_date', '发布日期')
        //     ->setFormat('Y-m-d')
        //     ->setRequired('请选择日期');

        // DateTime picker
        // $form->datetime('publish_time', '发布时间')
        //     ->setFormat('Y-m-d H:i:s');

        // Time picker
        // $form->time('start_time', '开始时间')
        //     ->setFormat('H:i:s');

        // Number input
        // $form->number('sort', '排序')
        //     ->setDefault(99)
        //     ->setMin(0)
        //     ->setMax(9999);

        // Price input
        // $form->number('price', '价格')
        //     ->setMin(0)
        //     ->setStep(0.01)
        //     ->setPrecision(2);

        // Single image upload
        // $form->image('cover', '封面图')
        //     ->setUploadUrl(U('upload/image'))
        //     ->setMaxSize(5 * 1024 * 1024) // 5MB
        //     ->setCrop(true) // Enable cropping
        //     ->setCropRatio([16, 9]);

        // Multiple image upload
        // $form->images('gallery', '图片集')
        //     ->setUploadUrl(U('upload/image'))
        //     ->setMaxCount(9)
        //     ->setMaxSize(2 * 1024 * 1024); // 2MB each

        // File upload
        // $form->file('attachment', '附件')
        //     ->setUploadUrl(U('upload/file'))
        //     ->setAccept(['pdf', 'doc', 'docx', 'xls', 'xlsx']);

        // District selector
        // $form->district('district', '地区')
        //     ->setLevel(3); // Province, City, Area

        // Password input
        // $form->password('password', '密码')
        //     ->setMinLength(6)
        //     ->setRequired('请输入密码');

        // URL input
        // $form->url('website', '网站')
        //     ->setPlaceholder('https://example.com');

        // Email input
        // $form->email('email', '邮箱')
        //     ->setRequired('请输入邮箱');

        // Phone input
        // $form->phone('telephone', '电话')
        //     ->setRequired('请输入电话号码');

        // Form group (organize fields)
        // $form->group('basic', '基本信息', [
        //     $form->text('name', '名称'),
        //     $form->text('code', '编码')
        // ]);
    }

    /**
     * Configure batch operations
     *
     * Batch actions appear in the table toolbar
     * Users select multiple rows and trigger actions
     *
     * @param TableContainer $container
     * @return void
     */
    protected function batchActions(TableContainer $container): void
    {
        // Enable batch delete
        $container->addBatchAction('delete', '批量删除', U('batchDelete'), [
            'confirm' => '确定要删除选中的记录吗？',
            'method' => 'post'
        ]);

        // Batch enable
        $container->addBatchAction('enable', '批量启用', U('batchEnable'), [
            'confirm' => '确定要启用选中的记录吗？',
            'method' => 'post'
        ]);

        // Batch disable
        $container->addBatchAction('disable', '批量禁用', U('batchDisable'), [
            'confirm' => '确定要禁用选中的记录吗？',
            'method' => 'post'
        ]);

        // Custom batch action
        // $container->addBatchAction('export', '批量导出', U('batchExport'), [
        //     'method' => 'post',
        //     'ajax' => true,
        //     'showProgress' => true
        // ]);
    }

    /**
     * Batch delete handler
     *
     * @return void
     */
    public function batchDelete()
    {
        $ids = I('post.ids', []);
        if (empty($ids)) {
            $this->error('请选择要删除的记录');
        }

        $id_array = is_array($ids) ? $ids : explode(',', $ids);
        $id_array = array_map('intval', $id_array);

        // TODO: Add dependency checks
        // foreach ($id_array as $id) {
        //     if (D('Related')->where(['{{TABLE_NAME}}_id' => $id])->count()) {
        //         $this->error('ID ' . $id . ' 正在使用中');
        //     }
        // }

        $result = D('{{MODEL_NAME}}')->where(['id' => ['IN', $id_array]])->delete();

        if ($result === false) {
            $this->error('删除失败');
        }

        $this->success('删除成功');
    }

    /**
     * Batch enable handler
     *
     * @return void
     */
    public function batchEnable()
    {
        $ids = I('post.ids', []);
        if (empty($ids)) {
            $this->error('请选择要启用的记录');
        }

        $id_array = is_array($ids) ? $ids : explode(',', $ids);
        $result = D('{{MODEL_NAME}}')->where(['id' => ['IN', $id_array]])->setField('status', DBCont::NORMAL_STATUS);

        if ($result === false) {
            $this->error('操作失败');
        }

        $this->success('启用成功');
    }

    /**
     * Batch disable handler
     *
     * @return void
     */
    public function batchDisable()
    {
        $ids = I('post.ids', []);
        if (empty($ids)) {
            $this->error('请选择要禁用的记录');
        }

        $id_array = is_array($ids) ? $ids : explode(',', $ids);
        $result = D('{{MODEL_NAME}}')->where(['id' => ['IN', $id_array]])->setField('status', DBCont::DISABLE_STATUS);

        if ($result === false) {
            $this->error('操作失败');
        }

        $this->success('禁用成功');
    }

    /**
     * Export data (CSV/Excel)
     *
     * @return void
     */
    public function export()
    {
        $map = $this->buildSearchMap(I('get.'));
        $list = D('{{MODEL_NAME}}')->where($map)->select();

        // TODO: Implement export logic
        // Use: phpoffice/phpspreadsheet

        $filename = '{{MODEL_TITLE}}_' . date('YmdHis') . '.csv';
        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="' . $filename . '"');

        $output = fopen('php://output', 'w');
        fputcsv($output, ['ID', '名称', '状态', '创建时间']);

        foreach ($list as $item) {
            fputcsv($output, [
                $item['id'],
                $item['{{TABLE_NAME}}_name'],
                $item['status'] == 1 ? '启用' : '禁用',
                date('Y-m-d H:i:s', $item['create_time'])
            ]);
        }

        fclose($output);
        exit;
    }

    /**
     * Detail view
     *
     * @return void
     */
    public function detail()
    {
        $id = I('get.id', 0, 'intval');
        $data = D('{{MODEL_NAME}}')->find($id);

        if (!$data) {
            $this->error('记录不存在');
        }

        // TODO: Prepare related data
        // $data['related'] = D('Related')->where(['{{TABLE_NAME}}_id' => $id])->select();

        $this->assign('data', $data);
        $this->display();
    }

    /**
     * Clear cache helper
     *
     * @return void
     */
    protected function clearCache(): void
    {
        // Clear detail cache
        // \Qscmf\Lib\Cache\QscmfCache::clearByTag('{{TABLE_NAME}}_detail');

        // Clear list cache
        // \Qscmf\Lib\Cache\QscmfCache::clearByTag('{{TABLE_NAME}}_list');
    }
}
