<?php
/**
 * {{MODEL_TITLE}} Admin Controller (v14 - AntdAdmin React Components)
 *
 * Generated by qscmf-backend skill
 * Framework: QSCMF v14.x (ThinkPHP 3.2 + AntdAdmin Component API + Inertia.js)
 *
 * IMPORTANT: This template uses the NEW AntdAdmin\Component API for React rendering.
 * For backward compatibility with ListBuilder API, set ANTD_ADMIN_BUILDER_ENABLE=false
 * or use v13 templates.
 *
 * API Options in v14:
 * 1. AntdAdmin\Component (this template): React rendering, modern UI
 *    - Use: new \AntdAdmin\Component\Table()
 *    - Rendering: React/AntdAdmin components
 * 2. ListBuilder API (legacy): See v13 templates
 *    - Use: $this->builder()
 *    - Rendering: jQuery or React (controlled by ANTD_ADMIN_BUILDER_ENABLE)
 *
 * Manual TODO Checklist:
 * [ ] 1. Update namespace if not in Admin\Module
 * [ ] 2. Verify all column types in buildTableColumns()
 * [ ] 3. Configure validation rules in Model
 * [ ] 4. Add business logic to add()/edit() methods
 * [ ] 5. Add dependency checks in delete() method
 * [ ] 6. Configure permissions in admin_menu table
 * [ ] 7. Test CRUD operations
 * [ ] 8. Add Inertia.js navigation if needed
 *
 * @package Admin\Controller
 */

namespace Admin\Controller;

use Gy_Library\GyListController;
use Gy_Library\DBCont;
use AntdAdmin\Component\Table;
use AntdAdmin\Component\Table\Pagination;
use AntdAdmin\Component\Form;
use AntdAdmin\Component\Modal\Modal;
use AntdAdmin\Component\ColumnType\RuleType\Required;

class {{MODEL}}Controller extends GyListController
{
    /**
     * Model name (auto-instantiated as D('{{MODEL_NAME}}'))
     *
     * @var string
     */
    protected $modelName = '{{MODEL_NAME}}';

    /**
     * Table name (optional, defaults to {{TABLE_NAME}})
     *
     * @var string
     */
    protected $tableName = '{{TABLE_NAME}}';

    /**
     * Form modal width
     *
     * @var string
     */
    protected $formWidth = '800px';

    /**
     * List page - Main CRUD interface
     *
     * Uses AntdAdmin\Component\Table for React rendering (v14)
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/index
     * Method: GET
     *
     * @return void
     */
    public function index()
    {
        // Step 1: Build search conditions
        $get_data = I('get.');
        $map = [];
        $this->buildSearchWhere($get_data, $map);

        // Step 2: Get pagination
        $model = D($this->modelName);
        $count = $model->where($map)->count();
        $per_page = C('ADMIN_PER_PAGE_NUM', null, false);

        if ($per_page === false) {
            $page = new \Gy_Library\GyPage($count);
        } else {
            $page = new \Gy_Library\GyPage($count, $per_page);
        }

        // Step 3: Get data
        $data_list = $model->where($map)
            ->order('id desc')
            ->page($page->nowPage, $page->listRows)
            ->select();

        // Step 4: Create AntdAdmin Table component
        $table = new Table();
        $table->setMetaTitle('{{MODEL_TITLE}}列表')
            ->actions(function (Table\ActionsContainer $container) {
                $this->buildTopActions($container);
            })
            ->columns(function (Table\ColumnsContainer $container) {
                $this->buildTableColumns($container);
            })
            ->setDataSource($data_list)
            ->setPagination(new Pagination($page->nowPage, $page->listRows, $count))
            ->setSearch(false)
            ->render();
    }

    /**
     * Add new record - Form page
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/add
     * Method: GET/POST
     *
     * @return mixed
     */
    public function add()
    {
        if (IS_POST) {
            parent::autoCheckToken();
            $data = I('post.');

            $model = D($this->modelName);
            $result = $model->createAdd($data);

            if ($result === false) {
                $this->error($model->getError());
            }

            sysLogs('新增{{MODEL_TITLE}}, id:' . $result);
            $this->success('添加成功');
        } else {
            $form = new Form();
            $form->setSubmitRequest('post', U('add'))
                ->setInitialValues($this->getFormDefaults())
                ->columns(function (Form\ColumnsContainer $columns) {
                    $this->buildFormColumns($columns);
                })
                ->actions(function (Form\ActionsContainer $actions) {
                    $actions->button('提交')->submit();
                    $actions->button('重置')->reset();
                });

            return $form->render();
        }
    }

    /**
     * Edit existing record
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/edit
     * Method: GET/POST
     * Query: id={record_id}
     *
     * @return mixed
     */
    public function edit()
    {
        $id = I('get.id', 0, 'intval');
        $data = D($this->modelName)->find($id);

        if (!$data) {
            $this->error('记录不存在');
        }

        if (IS_POST) {
            parent::autoCheckToken();
            $post_data = I('post.');

            $model = D($this->modelName);
            $result = $model->createSave($post_data);

            if ($result === false) {
                $this->error($model->getError());
            }

            sysLogs('编辑{{MODEL_TITLE}}, id:' . $id);
            $this->success('保存成功');
        } else {
            $form = new Form();
            $form->setSubmitRequest('post', U('edit', ['id' => $id]))
                ->setInitialValues($data)
                ->columns(function (Form\ColumnsContainer $columns) {
                    $this->buildFormColumns($columns);
                })
                ->actions(function (Form\ActionsContainer $actions) {
                    $actions->button('提交')->submit();
                    $actions->button('重置')->reset();
                });

            return $form->render();
        }
    }

    /**
     * Delete record(s)
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/delete
     * Method: POST/GET
     *
     * @return void
     */
    public function delete()
    {
        $ids = I('ids');
        if (!$ids) {
            $this->error('请选择要删除的数据');
        }

        if (is_string($ids)) {
            $ids = explode(',', $ids);
        }

        // TODO: Add dependency checks before delete
        // foreach ($ids as $id) {
        //     if (D('RelatedTable')->where([$this->tableName . '_id' => $id])->count() > 0) {
        //         $this->error('ID ' . $id . ' 正在使用中，无法删除');
        //     }
        // }

        $result = D($this->modelName)->where(['id' => ['in', $ids]])->delete();

        if ($result === false) {
            $this->error(D($this->modelName)->getError());
        }

        sysLogs('删除{{MODEL_TITLE}}, ids: ' . implode(',', $ids));
        $this->success('删除成功');
    }

    /**
     * Forbid (disable) records
     *
     * @return void
     */
    public function forbid()
    {
        $ids = I('ids');
        if (!$ids) {
            $this->error('请选择要禁用的数据');
        }

        if (is_string($ids)) {
            $ids = explode(',', $ids);
        }

        $result = D($this->modelName)
            ->where(['id' => ['in', $ids]])
            ->setField('status', DBCont::DISABLE_STATUS);

        if ($result === false) {
            $this->error('操作失败');
        }

        sysLogs('禁用{{MODEL_TITLE}}, ids: ' . implode(',', $ids));
        $this->success('禁用成功');
    }

    /**
     * Resume (enable) records
     *
     * @return void
     */
    public function resume()
    {
        $ids = I('ids');
        if (!$ids) {
            $this->error('请选择要启用的数据');
        }

        if (is_string($ids)) {
            $ids = explode(',', $ids);
        }

        $result = D($this->modelName)
            ->where(['id' => ['in', $ids]])
            ->setField('status', DBCont::NORMAL_STATUS);

        if ($result === false) {
            $this->error('操作失败');
        }

        sysLogs('启用{{MODEL_TITLE}}, ids: ' . implode(',', $ids));
        $this->success('启用成功');
    }

    /**
     * Build search conditions
     *
     * @param array $get_data GET parameters
     * @param array &$map Where conditions
     * @return void
     */
    protected function buildSearchWhere($get_data, &$map)
    {
        // Keyword search
        if (!empty($get_data['keyword'])) {
            $map['{{TABLE_NAME}}_name'] = ['like', '%' . $get_data['keyword'] . '%'];
        }

        // Status filter
        if (isset($get_data['status']) && $get_data['status'] !== '') {
            $map['status'] = $get_data['status'];
        }

        // Date range filter (use parse method for date_range type)
        // if (!empty($get_data['date_range'])) {
        //     $map = array_merge($map, \Qscmf\Builder\ListSearchType\DateRange::parse(
        //         'date_range',
        //         'create_time',
        //         $get_data
        //     ));
        // }
    }

    /**
     * Build top action buttons
     *
     * @param Table\ActionsContainer $container
     * @return void
     */
    protected function buildTopActions(Table\ActionsContainer $container)
    {
        // Add new button with modal
        $container->button('新增')
            ->setProps(['type' => 'primary'])
            ->modal((new Modal())
                ->setWidth($this->formWidth)
                ->setUrl(U('add'))
                ->setTitle('新增{{MODEL_TITLE}}'));

        // Batch operations
        $container->forbid();
        $container->resume();
        $container->delete();
        $container->editSave();
    }

    /**
     * Build table columns using AntdAdmin Component API
     *
     * Available column types:
     * - text($field, $title): Text column
     * - select($field, $title): Select column with enum
     * - date($field, $title): Date column
     * - datetime($field, $title): DateTime column
     * - image($field, $title): Image column
     * - number($field, $title): Number column
     * - money($field, $title): Money column
     * - action($field, $title): Action column
     *
     * Column methods:
     * - setSearch(bool): Enable/disable search
     * - setValueEnum(array): Set enum values
     * - setBadge(array): Set badge colors
     * - editable(): Enable inline editing
     * - setFormItemWidth(int): Set width (24 = 100%)
     *
     * @param Table\ColumnsContainer $container
     * @return void
     */
    protected function buildTableColumns(Table\ColumnsContainer $container)
    {
{{TABLE_COLUMNS}}
        // ========== COLUMN EXAMPLES ==========

        // ID column
        // $container->text('id', 'ID')->setSearch(false);

        // Text column with search
        // $container->text('{{TABLE_NAME}}_name', '名称')
        //     ->setSearch(true);

        // Select column with badge
        // $container->select('status', '状态')
        //     ->setValueEnum(DBCont::getStatusList())
        //     ->setBadge([1 => 'success', 0 => 'default'])
        //     ->setSearch(true);

        // Date column
        // $container->datetime('create_time', '创建时间')
        //     ->setSearch(true);

        // Number column with inline edit
        // $container->number('sort', '排序')
        //     ->editable()
        //     ->setSearch(false);

        // Image column
        // $container->image('cover', '封面');

        // ========== ACTION COLUMN (must be last) ==========
        $container->action('', '操作')
            ->actions(function (Table\ColumnType\ActionsContainer $container) {
                $container->edit()->modal(
                    (new Modal())
                        ->setWidth($this->formWidth)
                        ->setUrl(U('edit', ['id' => '__id__']))
                        ->setTitle('编辑')
                );
                $container->forbid();
                $container->resume();
                $container->delete();
            });
    }

    /**
     * Build form columns using AntdAdmin Component API
     *
     * Available field types:
     * - text($field, $title): Text input
     * - textarea($field, $title): Textarea
     * - number($field, $title): Number input
     * - money($field, $title): Money input
     * - select($field, $title): Select dropdown
     * - radio($field, $title): Radio buttons
     * - checkbox($field, $title): Checkbox group
     * - date($field, $title): Date picker
     * - datetime($field, $title): DateTime picker
     * - image($field, $title): Image upload
     * - file($field, $title): File upload
     * - ueditor($field, $title): Rich text editor
     * - password($field, $title): Password input
     * - hidden($field, $title): Hidden field
     *
     * Validation:
     * - addRule(new Required()): Required field
     * - addRule(new Length($min, $max)): Length validation
     * - addRule(new Email()): Email validation
     *
     * @param Form\ColumnsContainer $columns
     * @return void
     */
    protected function buildFormColumns(Form\ColumnsContainer $columns)
    {
{{FORM_COLUMNS}}
        // ========== FORM FIELD EXAMPLES ==========

        // Text input (required, full width)
        // $columns->text('{{TABLE_NAME}}_name', '名称')
        //     ->addRule(new Required())
        //     ->setFormItemWidth(24);

        // Textarea
        // $columns->textarea('description', '描述')
        //     ->setFormItemWidth(24);

        // Rich text editor
        // $columns->ueditor('content', '内容')
        //     ->setFormItemWidth(24);

        // Select dropdown
        // $columns->select('cate_id', '分类')
        //     ->setValueEnum(D('Category')->getField('id,name'))
        //     ->addRule(new Required())
        //     ->setFormItemWidth(24);

        // Radio buttons
        // $columns->radio('status', '状态')
        //     ->setValueEnum(DBCont::getStatusList())
        //     ->setFormItemWidth(24);

        // Image upload with crop
        // $columns->image('cover_id', '封面图')
        //     ->setUploadRequest(\FormItem\ObjectStorage\Lib\Common::genItemDataUrl('image'))
        //     ->setCrop('16/9')
        //     ->setFormItemWidth(24);

        // Number input (half width)
        // $columns->number('sort', '排序')
        //     ->setFormItemWidth(12);

        // Status select (half width)
        // $columns->select('status', '状态')
        //     ->setValueEnum(DBCont::getStatusList())
        //     ->addRule(new Required())
        //     ->setFormItemWidth(12);
    }

    /**
     * Get default form values for add
     *
     * @return array
     */
    protected function getFormDefaults(): array
    {
        return [
            'status' => DBCont::NORMAL_STATUS,
            'sort' => 99,
        ];
    }
}
