<?php
/**
 * {{MODEL_TITLE}} Test Case
 *
 * Generated by qscmf-backend skill
 * Framework: QSCMF v14.x (PHPUnit 10)
 *
 * Manual TODO Checklist:
 * [ ] 1. Implement test cases
 * [ ] 2. Add data providers for edge cases
 * [ ] 3. Add mock objects for external dependencies
 * [ ] 4. Run tests: vendor/bin/phpunit lara/tests/Feature/{{MODEL}}Test.php
 *
 * @package Tests\Feature
 */

namespace Tests\Feature;

use Tests\TestCase;
use Gy_Library\DBCont;

class {{MODEL}}Test extends TestCase
{
    /**
     * Test index list
     *
     * @return void
     */
    public function test_index_returns_list(): void
    {
        $response = $this->get('/api/{{model}}');

        $response->assertStatus(200)
            ->assertJsonStructure([
                'status',
                'data' => [
                    '*' => ['id', '{{TABLE_NAME}}_name', 'status'],
                ],
                'meta' => ['total', 'page', 'page_size'],
            ]);
    }

    /**
     * Test index with pagination
     *
     * @return void
     */
    public function test_index_with_pagination(): void
    {
        $response = $this->get('/api/{{model}}?page=1&page_size=10');

        $response->assertStatus(200)
            ->assertJsonPath('meta.page', 1)
            ->assertJsonPath('meta.page_size', 10);
    }

    /**
     * Test index with status filter
     *
     * @return void
     */
    public function test_index_with_status_filter(): void
    {
        $response = $this->get('/api/{{model}}?status=' . DBCont::NORMAL_STATUS);

        $response->assertStatus(200);

        $data = $response->json('data');
        foreach ($data as $item) {
            $this->assertEquals(DBCont::NORMAL_STATUS, $item['status']);
        }
    }

    /**
     * Test create record
     *
     * @return void
     */
    public function test_create_{{model}}(): void
    {
        $data = [
            '{{TABLE_NAME}}_name' => 'Test {{MODEL_TITLE}}',
            'status' => DBCont::NORMAL_STATUS,
        ];

        $response = $this->postJson('/api/{{model}}', $data);

        $response->assertStatus(201)
            ->assertJson(['status' => true])
            ->assertJsonStructure(['data' => ['id']]);

        // Verify database
        $this->assertDatabaseHas('{{TABLE_NAME}}', [
            '{{TABLE_NAME}}_name' => 'Test {{MODEL_TITLE}}',
        ]);
    }

    /**
     * Test create with missing required field
     *
     * @return void
     */
    public function test_create_validation_error(): void
    {
        $data = [
            'status' => DBCont::NORMAL_STATUS,
            // Missing {{TABLE_NAME}}_name
        ];

        $response = $this->postJson('/api/{{model}}', $data);

        $response->assertStatus(422)
            ->assertJson(['status' => false]);
    }

    /**
     * Test get detail
     *
     * @return void
     */
    public function test_get_detail(): void
    {
        // Create test record first
        $id = D('{{MODEL}}')->add([
            '{{TABLE_NAME}}_name' => 'Test Detail',
            'status' => DBCont::NORMAL_STATUS,
            'create_time' => time(),
        ]);

        $response = $this->get("/api/{{model}}/{$id}");

        $response->assertStatus(200)
            ->assertJson(['status' => true])
            ->assertJsonPath('data.id', $id)
            ->assertJsonPath('data.{{TABLE_NAME}}_name', 'Test Detail');

        // Cleanup
        D('{{MODEL}}')->delete($id);
    }

    /**
     * Test get detail not found
     *
     * @return void
     */
    public function test_get_detail_not_found(): void
    {
        $response = $this->get('/api/{{model}}/999999');

        $response->assertStatus(404)
            ->assertJson(['status' => false]);
    }

    /**
     * Test update record
     *
     * @return void
     */
    public function test_update_{{model}}(): void
    {
        // Create test record
        $id = D('{{MODEL}}')->add([
            '{{TABLE_NAME}}_name' => 'Original Name',
            'status' => DBCont::NORMAL_STATUS,
            'create_time' => time(),
        ]);

        $updateData = [
            '{{TABLE_NAME}}_name' => 'Updated Name',
        ];

        $response = $this->putJson("/api/{{model}}/{$id}", $updateData);

        $response->assertStatus(200)
            ->assertJson(['status' => true]);

        // Verify update
        $this->assertDatabaseHas('{{TABLE_NAME}}', [
            'id' => $id,
            '{{TABLE_NAME}}_name' => 'Updated Name',
        ]);

        // Cleanup
        D('{{MODEL}}')->delete($id);
    }

    /**
     * Test delete record
     *
     * @return void
     */
    public function test_delete_{{model}}(): void
    {
        // Create test record
        $id = D('{{MODEL}}')->add([
            '{{TABLE_NAME}}_name' => 'To Be Deleted',
            'status' => DBCont::NORMAL_STATUS,
            'create_time' => time(),
        ]);

        $response = $this->delete("/api/{{model}}/{$id}");

        $response->assertStatus(200)
            ->assertJson(['status' => true]);

        // Verify deletion
        $this->assertDatabaseMissing('{{TABLE_NAME}}', [
            'id' => $id,
        ]);
    }

    /**
     * Test keyword search
     *
     * @return void
     */
    public function test_keyword_search(): void
    {
        // Create test records
        D('{{MODEL}}')->add([
            '{{TABLE_NAME}}_name' => 'Unique Test Name ABC',
            'status' => DBCont::NORMAL_STATUS,
            'create_time' => time(),
        ]);

        $response = $this->get('/api/{{model}}?keyword=Unique Test');

        $response->assertStatus(200)
            ->assertJson(['status' => true]);

        $data = $response->json('data');
        $this->assertGreaterThan(0, count($data));

        foreach ($data as $item) {
            $this->assertStringContainsString('Unique Test', $item['{{TABLE_NAME}}_name']);
        }
    }
}
