<?php
/**
 * {{MODEL_TITLE}} Admin Controller (v13 - Legacy jQuery)
 *
 * Generated by qscmf-backend skill
 * Framework: QSCMF v13.x (ThinkPHP 3.2 + ListBuilder)
 *
 * Manual TODO Checklist:
 * [ ] 1. Update namespace if not in Admin\Module
 * [ ] 2. Verify all field types in buildTableColumns()
 * [ ] 3. Configure validation rules in Model
 * [ ] 4. Add business logic to save() method
 * [ ] 5. Add dependency checks in delete() method
 * [ ] 6. Configure permissions in admin_menu table
 * [ ] 7. Test CRUD operations
 *
 * @package Admin\Controller
 */

namespace Admin\Controller;

use Admin\Controller\QsListController;
use Gy_Library\DBCont;

class {{MODEL}}Controller extends QsListController
{
    /**
     * Model name (auto-instantiated as D('{{MODEL_NAME}}'))
     *
     * @var string
     */
    protected $modelName = '{{MODEL_NAME}}';

    /**
     * Table name (optional, defaults to {{TABLE_NAME}})
     *
     * @var string
     */
    protected $tableName = '{{TABLE_NAME}}';

    /**
     * Primary key field (default: 'id')
     *
     * @var string
     */
    protected $pk = 'id';

    /**
     * Enable soft delete (if table has delete_time field)
     *
     * @var bool
     */
    protected $softDelete = false;

    /**
     * List page - Main CRUD interface
     *
     * Displays table with:
     * - Search form (top)
     * - Data table (center)
     * - Pagination (bottom)
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/index
     * Method: GET
     *
     * @return void
     */
    public function index()
    {
        // Step 1: Build search conditions from GET parameters
        $map = $this->buildSearchMap(I('get.'));

        // Step 2: Get base query with conditions
        $model = D('{{MODEL_NAME}}')->where($map);

        // Step 3: Get total count for pagination
        $total = $model->count();

        // Step 4: Create ListBuilder instance
        $builder = $this->builder();

        // Step 5: Configure table columns
        $this->buildTableColumns($builder);

        // Step 6: Configure search form
        $this->buildSearchForm($builder);

        // Step 7: Configure action buttons
        $this->buildButtons($builder);

        // Step 8: Set data with pagination
        $list = $model->order('id desc')->select();
        $builder->setData($list);

        // Step 9: Display the page
        $builder->display();
    }

    /**
     * Add new record form
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/add
     * Method: GET
     *
     * @return void
     */
    public function add()
    {
        $builder = $this->builder();
        $this->buildFormItems($builder);
        $builder->addFormItem('is_submit', 'hidden', 1);
        $builder->display();
    }

    /**
     * Edit existing record
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/edit
     * Method: GET
     * Query: id={record_id}
     *
     * @return void
     */
    public function edit()
    {
        $id = I('get.id', 0, 'intval');
        $data = D('{{MODEL_NAME}}')->find($id);

        if (!$data) {
            $this->error('记录不存在');
        }

        $builder = $this->builder();
        $this->buildFormItems($builder);
        $builder->setData($data);
        $builder->display();
    }

    /**
     * Save record (create or update)
     *
     * Handles both create (add) and update (edit) operations
     * Triggered by form submission from add() and edit() pages
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/save
     * Method: POST
     *
     * @return void Redirects to index() or shows error
     */
    public function save()
    {
        // Get POST data
        $data = I('post.');

        // Validate data
        if (empty($data['{{TABLE_NAME}}_name'])) {
            $this->error('{{MODEL_TITLE}}名称不能为空');
        }

        // Start transaction
        D('{{MODEL_NAME}}')->startTrans();
        try {
            // TODO: Add your business logic here
            // Example: Process tags
            // if (isset($data['tags'])) {
            //     $data['tags'] = implode(',', $data['tags']);
            // }

            // Example: Upload image
            // if (isset($_FILES['cover']) && $_FILES['cover']['error'] == 0) {
            //     $upload_result = $this->uploadImage('cover');
            //     if (!$upload_result['status']) {
            //         E($upload_result['msg']);
            //     }
            //     $data['cover'] = $upload_result['id'];
            // }

            // Call parent save method
            $result = parent::save($data);

            if ($result === false) {
                E(D('{{MODEL_NAME}}')->getError());
            }

            D('{{MODEL_NAME}}')->commit();

            // TODO: Clear related caches if needed
            // D('{{MODEL_NAME}}')->clearCache();

            $this->success('保存成功', U('index'));

        } catch (\Exception $e) {
            D('{{MODEL_NAME}}')->rollback();
            $this->error($e->getMessage());
        }
    }

    /**
     * Delete record
     *
     * URL: /admin/{{MODULE}}/{{MODEL}}/delete
     * Method: GET
     * Query: ids={comma_separated_ids}
     *
     * @return void
     */
    public function delete()
    {
        $ids = I('get.ids');
        if (empty($ids)) {
            $this->error('请选择要删除的记录');
        }

        $id_array = explode(',', $ids);
        $id_array = array_map('intval', $id_array);

        // TODO: Add dependency checks
        // Example: Check if used in other tables
        // foreach ($id_array as $id) {
        //     if (D('OtherTable')->where(['{{TABLE_NAME}}_id' => $id])->count()) {
        //         $this->error('该{{MODEL_TITLE}}正在使用中，无法删除');
        //     }
        // }

        // TODO: If using soft delete
        // D('{{MODEL_NAME}}')->where(['id' => ['IN', $id_array]])->setField('delete_time', time());
        // $this->success('删除成功', U('index'));

        // Hard delete (default)
        $result = D('{{MODEL_NAME}}')->where(['id' => ['IN', $id_array]])->delete();

        if ($result === false) {
            $this->error('删除失败');
        }

        $this->success('删除成功', U('index'));
    }

    /**
     * Toggle status (forbid/resume)
     *
     * @param string $type 'forbid' to disable, 'resume' to enable
     * @param array $ids Record IDs to process
     * @return array JSON response for AJAX
     */
    public function toggleStatus($type, $ids)
    {
        $targetStatus = ($type === 'forbid') ? DBCont::DISABLE_STATUS : DBCont::NORMAL_STATUS;

        $id_array = is_array($ids) ? $ids : explode(',', $ids);
        $result = D('{{MODEL_NAME}}')->where(['id' => ['IN', $id_array]])->setField('status', $targetStatus);

        if ($result === false) {
            return ['status' => false, 'msg' => '操作失败'];
        }

        return ['status' => true, 'msg' => '操作成功'];
    }

    /**
     * Build search conditions from GET parameters
     *
     * Supports:
     * - Keyword search (multi-field)
     * - Exact match filters
     * - Date range filters
     * - Status filters
     *
     * @param array $search GET parameters
     * @return array ThinkPHP where conditions
     */
    protected function buildSearchMap(array $search): array
    {
        $map = [];

        // Keyword search (multi-field)
        if (!empty($search['keyword'])) {
            $map['{{TABLE_NAME}}_name|{{TABLE_NAME}}_code'] = ['like', '%' . $search['keyword'] . '%'];
        }

        // Status filter (supports 0 value)
        if (isset($search['status']) && $search['status'] !== '') {
            $map['status'] = $search['status'];
        }

        // Category filter
        if (!empty($search['cate_id'])) {
            $map['cate_id'] = $search['cate_id'];
        }

        // Date range filter
        if (!empty($search['start_time'])) {
            $map['create_time'][] = ['egt', strtotime($search['start_time'])];
        }
        if (!empty($search['end_time'])) {
            $map['create_time'][] = ['elt', strtotime($search['end_time'])];
        }

        return $map;
    }

    /**
     * Build table columns
     *
     * ListBuilder column types:
     * - text: Regular text column
     * - status: Status badge (uses options array)
     * - icon: Icon display
     * - date: Date format
     * - time: Time format
     * - picture: Single image
     * - pictures: Multiple images
     * - type: Custom type mapping
     * - fun: Custom function callback
     * - a: Link
     * - self: Custom template file
     * - num: Number with format
     * - checkbox: Checkbox selection
     * - select: Display value from options
     * - select2: Enhanced select
     * - textarea: Truncated text
     *
     * @param \Qscmf\Builder\ListBuilder $builder
     * @return void
     */
    protected function buildTableColumns($builder)
    {
{{TABLE_COLUMNS}}
        // Common column examples:
        // $builder->addTableColumn('id', 'ID');

        // Text column with custom width
        // $builder->addTableColumn('{{TABLE_NAME}}_name', '名称', '', '', 'style="width:200px"');

        // Status column with color mapping
        // $builder->addTableColumn('status', '状态', [
        //     1 => '<span class="label label-success">启用</span>',
        //     0 => '<span class="label label-default">禁用</span>'
        // ]);

        // Date column
        // $builder->addTableColumn('create_time', '创建时间', 'date_format', 'Y-m-d H:i');

        // Image column
        // $builder->addTableColumn('cover', '封面', 'picture');

        // Custom function callback
        // $builder->addTableColumn('custom', '自定义', 'fun', function($value, $data) {
        //     return $data['field1'] . ' - ' . $data['field2'];
        // });

        // Link column
        // $builder->addTableColumn('id', '操作', 'a', [
        //     'title' => '查看详情',
        //     'href' => U('detail', ['id' => '@id@'])
        // ]);
    }

    /**
     * Build search form items
     *
     * ListBuilder search item types:
     * - text: Text input (LIKE query)
     * - select: Dropdown select
     * - date: Date picker
     * - time: Time picker
     * - datetime: DateTime picker
     * - between: Range input (e.g., price min,max)
     * - checkbox: Multiple checkboxes
     *
     * @param \Qscmf\Builder\ListBuilder $builder
     * @return void
     */
    protected function buildSearchForm($builder)
    {
{{SEARCH_ITEMS}}
        // Common search item examples:
        // $builder->addSearchItem('keyword', 'text', '关键词');

        // Status select dropdown
        // $builder->addSearchItem('status', 'select', '状态', [
        //     '' => '全部',
        //     1 => '启用',
        //     0 => '禁用'
        // ]);

        // Category dropdown (from DBCont or Model)
        // $builder->addSearchItem('cate_id', 'select', '分类', D('Category')->getFieldOptions());

        // Date range
        // $builder->addSearchItem('create_time', 'date', '创建时间');

        // Number range
        // $builder->addSearchItem('price', 'between', '价格范围');
    }

    /**
     * Build form items for add/edit
     *
     * ListBuilder form item types:
     * - text: Single line text
     * - textarea: Multi-line text
     * - editor: Rich text editor (UEditor)
     * - select: Dropdown select
     * - radio: Radio buttons
     * - checkbox: Checkboxes
     * - date: Date picker
     * - time: Time picker
     * - datetime: DateTime picker
     * - picture: Single image upload
     * - pictures: Multiple image upload
     * - file: File upload
     * - files: Multiple file upload
     * - num: Number input
     * - hidden: Hidden field
     * - password: Password input
     *
     * @param \Qscmf\Builder\ListBuilder $builder
     * @return void
     */
    protected function buildFormItems($builder)
    {
{{FORM_ITEMS}}
        // Common form item examples:
        // $builder->addFormItem('{{TABLE_NAME}}_name', 'text', '名称', '请输入{{MODEL_TITLE}}名称');

        // Required field
        // $builder->addFormItem('{{TABLE_NAME}}_code', 'text', '编码', '请输入编码', true);

        // Textarea
        // $builder->addFormItem('description', 'textarea', '描述', '请输入描述');

        // Rich text editor
        // $builder->addFormItem('content', 'editor', '内容');

        // Select dropdown
        // $builder->addFormItem('cate_id', 'select', '分类', D('Category')->getFieldOptions());

        // Radio buttons
        // $builder->addFormItem('status', 'radio', '状态', [1 => '启用', 0 => '禁用']);

        // Date picker
        // $builder->addFormItem('publish_date', 'date', '发布日期');

        // Image upload
        // $builder->addFormItem('cover', 'picture', '封面图');

        // Multiple image upload
        // $builder->addFormItem('images', 'pictures', '图片集');

        // File upload
        // $builder->addFormItem('attachment', 'file', '附件');
    }

    /**
     * Build action buttons
     *
     * Top button types (addTopButton):
     * - addnew: Add new record
     * - submit: Submit form
     * - resume: Enable records
     * - forbid: Disable records
     * - delete: Delete records
     * - custom: Custom button
     *
     * Right button types (addRightButton):
     * - edit: Edit record
     * - delete: Delete record
     * - forbid: Disable record
     * - resume: Enable record
     * - custom: Custom action
     *
     * @param \Qscmf\Builder\ListBuilder $builder
     * @return void
     */
    protected function buildButtons($builder)
    {
        // ========== TOP BUTTONS (page-level actions) ==========

        // Add new button
        $builder->addTopButton('addnew', [
            'title' => '新增{{MODEL_TITLE}}',
            'href' => U('add')
        ]);

        // Enable selected
        $builder->addTopButton('resume', [
            'title' => '启用',
            'href' => U('toggleStatus', ['type' => 'resume']),
            'ajax' => true,
            'confirm' => '确定要启用选中的记录吗？'
        ]);

        // Disable selected
        $builder->addTopButton('forbid', [
            'title' => '禁用',
            'href' => U('toggleStatus', ['type' => 'forbid']),
            'ajax' => true,
            'confirm' => '确定要禁用选中的记录吗？'
        ]);

        // Delete selected
        $builder->addTopButton('delete', [
            'title' => '删除',
            'href' => U('delete'),
            'ajax' => true,
            'confirm' => '确定要删除选中的记录吗？'
        ]);

        // Custom top button
        // $builder->addTopButton('custom', [
        //     'title' => '导出',
        //     'href' => U('export'),
        //     'icon' => 'fa fa-download',
        //     'class' => 'btn btn-info'
        // ]);

        // ========== RIGHT BUTTONS (row-level actions) ==========

        // Edit button
        $builder->addRightButton('edit', [
            'title' => '编辑',
            'href' => U('edit', ['id' => '@id@'])
        ]);

        // Delete button
        $builder->addRightButton('delete', [
            'title' => '删除',
            'href' => U('delete', ['ids' => '@id@']),
            'confirm' => '确定要删除该记录吗？'
        ]);

        // Toggle status button
        // $builder->addRightButton('forbid', [
        //     'title' => '禁用',
        //     'href' => U('toggleStatus', ['type' => 'forbid', 'ids' => '@id@']),
        //     'ajax' => true
        // ]);

        // Custom right button
        // $builder->addRightButton('custom', [
        //     'title' => '查看',
        //     'href' => U('detail', ['id' => '@id@']),
        //     'icon' => 'fa fa-eye'
        // ]);
    }

    /**
     * Custom batch action example
     *
     * @return void
     */
    public function batchUpdate()
    {
        $ids = I('post.ids');
        $field = I('post.field');
        $value = I('post.value');

        if (empty($ids)) {
            $this->error('请选择要操作的记录');
        }

        $id_array = explode(',', $ids);
        $result = D('{{MODEL_NAME}}')->where(['id' => ['IN', $id_array]])->setField($field, $value);

        if ($result === false) {
            $this->error('操作失败');
        }

        $this->success('操作成功', U('index'));
    }

    /**
     * Export data example
     *
     * @return void
     */
    public function export()
    {
        $map = $this->buildSearchMap(I('get.'));
        $list = D('{{MODEL_NAME}}')->where($map)->select();

        // TODO: Implement export logic (CSV, Excel, etc.)
        // Vendor: phpoffice/phpspreadsheet

        $filename = '{{MODEL_TITLE}}_' . date('YmdHis') . '.csv';
        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="' . $filename . '"');

        $output = fopen('php://output', 'w');
        // Header row
        fputcsv($output, ['ID', '名称', '创建时间']);

        // Data rows
        foreach ($list as $item) {
            fputcsv($output, [
                $item['id'],
                $item['{{TABLE_NAME}}_name'],
                date('Y-m-d H:i:s', $item['create_time'])
            ]);
        }

        fclose($output);
        exit;
    }

    /**
     * Import data example
     *
     * @return void
     */
    public function import()
    {
        if (IS_POST) {
            $upload = I('file.file');
            if (empty($upload)) {
                $this->error('请选择要导入的文件');
            }

            // TODO: Parse CSV/Excel and import data
            // Validate each row before insert

            $this->success('导入成功', U('index'));
        }

        // Display upload form
        $this->display();
    }

    /**
     * Detail view example
     *
     * @return void
     */
    public function detail()
    {
        $id = I('get.id', 0, 'intval');
        $data = D('{{MODEL_NAME}}')->find($id);

        if (!$data) {
            $this->error('记录不存在');
        }

        // TODO: Prepare related data
        // $data['related_items'] = D('Related')->where(['{{TABLE_NAME}}_id' => $id])->select();

        $this->assign('data', $data);
        $this->display();
    }

    /**
     * Helper: Upload image
     *
     * @param string $field Field name
     * @return array Upload result
     */
    protected function uploadImage($field)
    {
        // QSCMF file upload helper
        $uploader = new \Gy_Library\GyUpload();
        $result = $uploader->upload($field);

        return $result;
    }

    /**
     * Helper: Clear cache
     *
     * @return void
     */
    protected function clearCache()
    {
        // Clear model cache
        // \Qscmf\Lib\Cache\QscmfCache::clearByTag('{{TABLE_NAME}}_list');
    }
}
