<?php
/**
 * {{MODEL_TITLE}} API Controller
 *
 * Generated by qscmf-backend skill
 * Framework: QSCMF v13.x
 *
 * Manual TODO Checklist:
 * [ ] 1. Configure authentication in $noAuthorization
 * [ ] 2. Add validation for each endpoint
 * [ ] 3. Implement business logic
 * [ ] 4. Add rate limiting if needed
 * [ ] 5. Test all endpoints
 *
 * @package Api\Controller
 */

namespace Api\Controller;

use Qscmf\Api\RestController;
use QscmfApiCommon\Cache\Response;
use Gy_Library\DBCont;

/**
 * {{MODEL_TITLE}} API Controller
 */
class {{MODEL}}Controller extends RestController
{
    /**
     * Model name
     *
     * @var string
     */
    protected $modelName = '{{MODEL_NAME}}';

    /**
     * Endpoints that don't require authentication
     *
     * @var array
     */
    protected $noAuthorization = ['gets', 'detail'];

    /**
     * Get list with pagination
     *
     * GET /api.php/{{MODEL}}/gets
     * Query: page, limit, keyword, status
     *
     * @return Response
     */
    public function gets(): Response
    {
        $get_data = I('get.');

        $page = (int)($get_data['page'] ?? 1);
        $limit = (int)($get_data['limit'] ?? 10);
        $keyword = $get_data['keyword'] ?? '';
        $status = $get_data['status'] ?? '';

        // Build query
        $where = [];
        if ($keyword) {
            $where['{{SEARCH_FIELD}}'] = ['like', '%' . $keyword . '%'];
        }
        if ($status !== '') {
            $where['status'] = $status;
        }

        // Get total count
        $total = D('{{MODEL_NAME}}')->where($where)->count();

        // Get list
        $list = D('{{MODEL_NAME}}')
            ->where($where)
            ->page($page, $limit)
            ->order('id desc')
            ->select();

        // Format data
        $data = $this->formatList($list);

        return new Response('成功', 1, [
            'list' => $data,
            'total' => $total,
            'page' => $page,
            'limit' => $limit
        ]);
    }

    /**
     * Get detail by ID
     *
     * GET /api.php/{{MODEL}}/detail
     * Query: id
     *
     * @return Response
     */
    public function detail(): Response
    {
        $id = I('get.id', 0, 'intval');

        if (!$id) {
            return new Response('参数错误', 0);
        }

        $data = D('{{MODEL_NAME}}')->find($id);

        if (!$data) {
            return new Response('记录不存在', 0);
        }

        $data = $this->formatDetail($data);

        return new Response('成功', 1, $data);
    }

    /**
     * Create new record
     *
     * POST /api.php/{{MODEL}}/save
     * Body: form data or JSON
     *
     * @return Response
     */
    public function save(): Response
    {
        if (!IS_POST) {
            return new Response('请求方法错误', 0);
        }

        $data = I('post.');

        // Validate required fields
        if (empty($data['{{TABLE_NAME}}_name'])) {
            return new Response('名称不能为空', 0);
        }

        // TODO: Add more validation
        // TODO: Add business logic

        $id = D('{{MODEL_NAME}}')->add($data);

        if ($id) {
            return new Response('创建成功', 1, ['id' => $id]);
        }

        return new Response('创建失败: ' . D('{{MODEL_NAME}}')->getError(), 0);
    }

    /**
     * Update record
     *
     * PUT /api.php/{{MODEL}}/update
     * Body: form data or JSON with id
     *
     * @return Response
     */
    public function update(): Response
    {
        if (!IS_PUT) {
            return new Response('请求方法错误', 0);
        }

        $data = I('put.');
        $id = $data['id'] ?? 0;

        if (!$id) {
            return new Response('参数错误', 0);
        }

        // Check record exists
        $exists = D('{{MODEL_NAME}}')->find($id);
        if (!$exists) {
            return new Response('记录不存在', 0);
        }

        // TODO: Add validation
        // TODO: Add business logic

        $result = D('{{MODEL_NAME}}')->where(['id' => $id])->save($data);

        if ($result !== false) {
            return new Response('更新成功', 1);
        }

        return new Response('更新失败: ' . D('{{MODEL_NAME}}')->getError(), 0);
    }

    /**
     * Delete record
     *
     * DELETE /api.php/{{MODEL}}/delete
     * Query: id
     *
     * @return Response
     */
    public function delete(): Response
    {
        if (!IS_DELETE) {
            return new Response('请求方法错误', 0);
        }

        $id = I('get.id', 0, 'intval');

        if (!$id) {
            return new Response('参数错误', 0);
        }

        // TODO: Add business logic (e.g., check dependencies)
        // if (D('OtherTable')->where(['{{TABLE_NAME}}_id' => $id])->count()) {
        //     return new Response('该记录正在使用中，无法删除', 0);
        // }

        $result = D('{{MODEL_NAME}}')->delete($id);

        if ($result) {
            return new Response('删除成功', 1);
        }

        return new Response('删除失败', 0);
    }

    /**
     * Batch delete records
     *
     * POST /api.php/{{MODEL}}/batchDelete
     * Body: ids (comma-separated or array)
     *
     * @return Response
     */
    public function batchDelete(): Response
    {
        if (!IS_POST) {
            return new Response('请求方法错误', 0);
        }

        $ids = I('post.ids');
        if (empty($ids)) {
            return new Response('请选择要删除的记录', 0);
        }

        $id_array = is_array($ids) ? $ids : explode(',', $ids);
        $id_array = array_map('intval', $id_array);

        $result = D('{{MODEL_NAME}}')->where(['id' => ['IN', $id_array]])->delete();

        if ($result !== false) {
            return new Response('删除成功', 1, ['count' => $result]);
        }

        return new Response('删除失败', 0);
    }

    /**
     * Toggle status
     *
     * POST /api.php/{{MODEL}}/toggleStatus
     * Body: id, status
     *
     * @return Response
     */
    public function toggleStatus(): Response
    {
        if (!IS_POST) {
            return new Response('请求方法错误', 0);
        }

        $id = I('post.id', 0, 'intval');
        $status = I('post.status', 0, 'intval');

        if (!$id) {
            return new Response('参数错误', 0);
        }

        if (!in_array($status, [DBCont::NORMAL_STATUS, DBCont::DISABLE_STATUS])) {
            return new Response('状态值不正确', 0);
        }

        $result = D('{{MODEL_NAME}}')->where(['id' => $id])->setField('status', $status);

        if ($result !== false) {
            return new Response('操作成功', 1);
        }

        return new Response('操作失败', 0);
    }

    /**
     * Get options for select
     *
     * GET /api.php/{{MODEL}}/options
     * Query: field (optional, default: name)
     *
     * @return Response
     */
    public function options(): Response
    {
        $field = I('get.field', 'name');

        $options = D('{{MODEL_NAME}}')
            ->where(['status' => DBCont::NORMAL_STATUS])
            ->getField('id,' . $field, true);

        $result = [];
        foreach ($options as $id => $value) {
            $result[] = [
                'value' => $id,
                'label' => $value
            ];
        }

        return new Response('成功', 1, $result);
    }

    /**
     * Format list data
     *
     * @param array $list List data
     * @return array
     */
    protected function formatList(array $list): array
    {
{{DATA_FORMAT}}
        // Default format
        $result = [];
        foreach ($list as $item) {
            $result[] = [
                'id' => (int)$item['id'],
                'name' => $item['{{TABLE_NAME}}_name'] ?? '',
                'status' => (int)$item['status'],
                'status_text' => DBCont::getStatusList()[$item['status']] ?? '',
                'create_time' => $item['create_time'] ?? 0,
                'create_time_text' => !empty($item['create_time']) ? date('Y-m-d H:i', $item['create_time']) : '',
            ];
        }
        return $result;
    }

    /**
     * Format detail data
     *
     * @param array $data Detail data
     * @return array
     */
    protected function formatDetail(array $data): array
    {
        // TODO: Add custom formatting
        $data['status_text'] = DBCont::getStatusList()[$data['status']] ?? '';
        $data['create_time_text'] = !empty($data['create_time']) ? date('Y-m-d H:i:s', $data['create_time']) : '';

        return $data;
    }
}
