<?php
/**
 * {{MODEL_TITLE}} Model
 *
 * Generated by qscmf-backend skill
 * Framework: QSCMF v13.x
 *
 * Manual TODO Checklist:
 * [ ] 1. Update validation rules in $_validate
 * [ ] 2. Configure auto-fill rules in $_auto
 * [ ] 3. Add relation definitions in $_link
 * [ ] 4. Implement custom business methods
 * [ ] 5. Add caching logic if needed
 *
 * @package Common\Model
 */

namespace Common\Model;

use Gy_Library\GyListModel;
use Gy_Library\DBCont;
use Qscmf\Lib\Cache\QscmfCache;

/**
 * {{MODEL_TITLE}} Model
 */
class {{MODEL_NAME}}Model extends GyListModel
{
    /**
     * Table name
     *
     * @var string
     */
    protected $tableName = '{{TABLE_NAME}}';

    /**
     * Primary key
     *
     * @var string
     */
    protected $pk = 'id';

    /**
     * Validation rules
     *
     * Format: [field, rule, message, condition, type]
     * - condition: 1 = must validate, 2 = validate if not empty, 3 = validate if exists
     * - type: regex, function, callback, confirm, equal, unique, in, notin, between, length
     *
     * @var array
     */
    protected $_validate = [
{{VALIDATE_RULES}}
        // Example validation rules:
        // ['{{TABLE_NAME}}_name', 'require', '{{MODEL_TITLE}}名称不能为空', self::MUST_VALIDATE],
        // ['{{TABLE_NAME}}_name', '1,200', '{{MODEL_TITLE}}名称长度不正确', self::VALUE_VALIDATE, 'length'],
        // ['email', 'email', '邮箱格式不正确', self::VALUE_VALIDATE],
        // ['code', 'unique', '编码已存在', self::MUST_VALIDATE],
        // ['status', [0, 1, 2], '状态值不正确', self::VALUE_VALIDATE, 'in'],
    ];

    /**
     * Auto-fill rules
     *
     * Format: [field, rule, condition, type]
     * - condition: 1 = insert, 2 = update, 3 = all
     * - type: function, callback, field, string, ignore
     *
     * @var array
     */
    protected $_auto = [
        ['create_time', 'time', self::MODEL_INSERT, 'function'],
        ['update_time', 'time', self::MODEL_UPDATE, 'function'],
        // ['create_uid', 'getUid', self::MODEL_INSERT, 'callback'],
        // ['update_uid', 'getUid', self::MODEL_BOTH, 'callback'],
    ];

    /**
     * Relation definitions
     *
     * @var array
     */
    protected $_link = [
        // Example relations:
        // 'Category' => [
        //     'mapping_type' => self::BELONGS_TO,
        //     'class_name' => 'Category',
        //     'foreign_key' => 'cate_id',
        //     'mapping_name' => 'category',
        //     'mapping_fields' => 'id,name',
        // ],
        // 'Items' => [
        //     'mapping_type' => self::HAS_MANY,
        //     'class_name' => '{{MODEL_NAME}}Item',
        //     'foreign_key' => '{{TABLE_NAME}}_id',
        //     'mapping_name' => 'items',
        // ],
    ];

    /**
     * Parse query conditions
     *
     * @param array $get_data GET parameters
     * @param array $map Reference to query conditions array
     * @return void
     */
    public function parse{{MODEL_NAME}}Map(array $get_data = [], array &$map = []): void
    {
        // Category filter
        if (isset($get_data['cate_id']) && !qsEmpty($get_data['cate_id'])) {
            $map['cate_id'] = $get_data['cate_id'];
        }

        // Status filter (supports 0 value)
        if (isset($get_data['status']) && $get_data['status'] !== '') {
            $map['status'] = $get_data['status'];
        }

        // Keyword search
        if (isset($get_data['keyword']) && !qsEmpty($get_data['keyword'])) {
            $map['title'] = ['like', '%' . $get_data['keyword'] . '%'];
        }

        // Time range filter
        if (isset($get_data['start_time']) && !qsEmpty($get_data['start_time'])) {
            $map['create_time'][] = ['egt', strtotime($get_data['start_time'])];
        }
        if (isset($get_data['end_time']) && !qsEmpty($get_data['end_time'])) {
            $map['create_time'][] = ['elt', strtotime($get_data['end_time'])];
        }
    }

    /**
     * Get record count
     *
     * @param array $map Query conditions
     * @return int
     */
    public function get{{MODEL_NAME}}Count(array $map = []): int
    {
        return (int)$this->where($map)->count();
    }

    /**
     * Get list with pagination
     *
     * @param array $map Query conditions
     * @param int|null $page Page number (null for all)
     * @param int $per_page Items per page
     * @return array
     */
    public function get{{MODEL_NAME}}List(array $map = [], ?int $page = null, ?int $per_page = 20): array
    {
        $model = $this->where($map);

        if (!is_null($page)) {
            $model->page($page, $per_page);
        }

        $list = (array)$model->order('sort asc, id desc')->select();

        // Format list data
        $this->formatList($list);

        return $list;
    }

    /**
     * Get detail by ID
     *
     * @param int $id Record ID
     * @return array|null
     */
    public function get{{MODEL_NAME}}Detail(int $id): ?array
    {
        $cache = new QscmfCache('{{TABLE_NAME_SNAKE}}_detail_' . $id, 3600);

        return $cache->remember(function() use ($id) {
            $data = $this->where(['id' => $id])->find();
            return $data ?: null;
        });
    }

    /**
     * Add record
     *
     * @param array $data Record data
     * @return int Record ID (0 on failure)
     */
    public function add{{MODEL_NAME}}(array $data): int
    {
        $this->startTrans();
        try {
            $id = $this->createAdd($data);
            if ($id === false) {
                E($this->getError());
            }

            // TODO: Add related data (tags, categories, etc.)
            // if (isset($data['tags'])) {
            //     D('{{MODEL_NAME}}Tag')->add{{MODEL_NAME}}Tags($id, $data['tags']);
            // }

            $this->commit();
            return $id;
        } catch (\Exception $e) {
            $this->rollback();
            $this->error = $e->getMessage();
            return 0;
        }
    }

    /**
     * Update record
     *
     * @param int $id Record ID
     * @param array $data Update data
     * @return bool
     */
    public function update{{MODEL_NAME}}(int $id, array $data): bool
    {
        $this->startTrans();
        try {
            $result = $this->where(['id' => $id])->save($data);
            if ($result === false) {
                E($this->getError());
            }

            // Clear detail cache
            $cache = new QscmfCache('{{TABLE_NAME_SNAKE}}_detail_' . $id);
            $cache->clear();

            // Clear list cache
            QscmfCache::clearByTag('{{TABLE_NAME_SNAKE}}_list');

            $this->commit();
            return true;
        } catch (\Exception $e) {
            $this->rollback();
            $this->error = $e->getMessage();
            return false;
        }
    }

    /**
     * Delete record
     *
     * @param int $id Record ID
     * @return bool
     */
    public function delete{{MODEL_NAME}}(int $id): bool
    {
        $this->startTrans();
        try {
            $result = $this->where(['id' => $id])->delete();
            if ($result === false) {
                E($this->getError());
            }

            // Clear cache
            $cache = new QscmfCache('{{TABLE_NAME_SNAKE}}_detail_' . $id);
            $cache->clear();
            QscmfCache::clearByTag('{{TABLE_NAME_SNAKE}}_list');

            $this->commit();
            return true;
        } catch (\Exception $e) {
            $this->rollback();
            $this->error = $e->getMessage();
            return false;
        }
    }

    /**
     * Disable records
     *
     * @param string|array $ids Record IDs
     * @return array Changed IDs
     */
    public function forbid($ids): array
    {
        return $this->changeStatus($ids, DBCont::NORMAL_STATUS, DBCont::DISABLE_STATUS);
    }

    /**
     * Enable records
     *
     * @param string|array $ids Record IDs
     * @return array Changed IDs
     */
    public function resume($ids): array
    {
        return $this->changeStatus($ids, DBCont::DISABLE_STATUS, DBCont::NORMAL_STATUS);
    }

    /**
     * Change status
     *
     * @param string|array $ids Record IDs
     * @param int $from Source status
     * @param int $to Target status
     * @return array Changed IDs
     */
    private function changeStatus($ids, int $from, int $to): array
    {
        $id_array = is_array($ids) ? $ids : explode(',', $ids);
        $id_array = array_filter($id_array);

        // Only change records matching source status
        $need_change_ids = $this->where([
            'id' => ['IN', $id_array],
            'status' => $from
        ])->getField('id', true);

        if (empty($need_change_ids)) {
            return [];
        }

        $this->where(['id' => ['IN', $need_change_ids]])->setField('status', $to);

        // Clear cache
        QscmfCache::clearByTag('{{TABLE_NAME_SNAKE}}_list');

        return $need_change_ids;
    }

    /**
     * Format list data
     *
     * @param array $list List data reference
     * @return void
     */
    public function formatList(array &$list): void
    {
        if (empty($list)) {
            return;
        }

        // Batch get related data (avoid N+1 query)
        $cate_ids = array_column($list, 'cate_id');
        $cate_ids = array_filter(array_unique($cate_ids));

        $cate_list = [];
        if (!empty($cate_ids)) {
            $cate_list = D('Cate')
                ->where(['id' => ['IN', $cate_ids]])
                ->getField('id,name', true);
        }

        // Format each record
        foreach ($list as &$item) {
            $item['cate_name'] = $cate_list[$item['cate_id']]['name'] ?? '';
            $item['status_text'] = DBCont::getStatusList()[$item['status']] ?? '';
            $item['cover_url'] = !empty($item['cover']) ? get_image_url($item['cover']) : '';
            $item['create_time_text'] = !empty($item['create_time']) ? date('Y-m-d H:i', $item['create_time']) : '';
        }
    }

    /**
     * Get status list
     *
     * @return array
     */
    public function getStatusList(): array
    {
        return DBCont::getStatusList();
    }

    /**
     * Get field options for select
     *
     * @param string $field Field name
     * @return array
     */
    public function getFieldOptions(string $field = 'name'): array
    {
        return $this->where(['status' => DBCont::NORMAL_STATUS])
            ->getField('id,' . $field, true);
    }

    /**
     * Get current user ID
     *
     * @return int
     */
    protected function getUid(): int
    {
        return (int)session('user_auth.uid');
    }
}
