<?php
/**
 * {{MODEL_TITLE}} Test Case
 *
 * Generated by qscmf-backend skill
 * Framework: QSCMF v13.x (PHPUnit 9.x)
 *
 * Manual TODO Checklist:
 * [ ] 1. Update test data for your model
 * [ ] 2. Add more test scenarios
 * [ ] 3. Mock external services
 * [ ] 4. Add edge case tests
 * [ ] 5. Run tests: vendor/bin/phpunit lara/tests/Feature/{{MODEL}}Test.php
 *
 * @package Lara\Tests\Feature
 */

namespace Lara\Tests\Feature;

use Lara\Tests\TestCase;
use Illuminate\Support\Facades\DB;
use Gy_Library\DBCont;

/**
 * {{MODEL_TITLE}} Test Case
 */
class {{MODEL}}Test extends TestCase
{
    /**
     * Table name
     *
     * @var string
     */
    protected string $table = '{{TABLE_NAME}}';

    /**
     * Test getting list
     *
     * @return void
     */
    public function testGetList(): void
    {
        $response = $this->get('/api.php/{{MODEL}}/gets');

        $response->assertStatus(200)
            ->assertJson(['status' => 1])
            ->assertJsonStructure([
                'status',
                'msg',
                'data' => [
                    'list',
                    'total',
                    'page',
                    'limit'
                ]
            ]);
    }

    /**
     * Test getting list with pagination
     *
     * @return void
     */
    public function testGetListWithPagination(): void
    {
        $response = $this->get('/api.php/{{MODEL}}/gets?page=1&limit=5');

        $response->assertStatus(200)
            ->assertJson(['status' => 1])
            ->assertJsonPath('data.page', 1)
            ->assertJsonPath('data.limit', 5);
    }

    /**
     * Test getting list with search
     *
     * @return void
     */
    public function testGetListWithSearch(): void
    {
        $response = $this->get('/api.php/{{MODEL}}/gets?keyword=test');

        $response->assertStatus(200)
            ->assertJson(['status' => 1]);
    }

    /**
     * Test getting list with status filter
     *
     * @return void
     */
    public function testGetListWithStatusFilter(): void
    {
        $response = $this->get('/api.php/{{MODEL}}/gets?status=1');

        $response->assertStatus(200)
            ->assertJson(['status' => 1]);

        // Verify all returned records have status = 1
        $data = json_decode($response->getContent(), true);
        foreach ($data['data']['list'] as $item) {
            $this->assertEquals(1, $item['status']);
        }
    }

    /**
     * Test getting detail
     *
     * @return void
     */
    public function testGetDetail(): void
    {
        // Create test data
        $id = DB::table($this->table)->insertGetId([
            // 'name' => 'Test {{MODEL_TITLE}}',
            // 'status' => DBCont::NORMAL_STATUS,
            // 'created_at' => now(),
            // 'updated_at' => now(),
        ]);

        $response = $this->get('/api.php/{{MODEL}}/detail?id=' . $id);

        $response->assertStatus(200)
            ->assertJson(['status' => 1]);

        // Cleanup
        DB::table($this->table)->delete($id);
    }

    /**
     * Test getting detail with invalid ID
     *
     * @return void
     */
    public function testGetDetailWithInvalidId(): void
    {
        $response = $this->get('/api.php/{{MODEL}}/detail?id=999999');

        $response->assertStatus(200)
            ->assertJson(['status' => 0]);
    }

    /**
     * Test creating record
     *
     * @return void
     */
    public function testCreate(): void
    {
        $data = [
            // 'name' => 'Test {{MODEL_TITLE}}',
            // 'status' => DBCont::NORMAL_STATUS,
        ];

        $response = $this->post('/api.php/{{MODEL}}/save', $data);

        $response->assertStatus(200)
            ->assertJson(['status' => 1])
            ->assertJsonStructure([
                'status',
                'msg',
                'data' => ['id']
            ]);

        // Cleanup
        $result = json_decode($response->getContent(), true);
        if (isset($result['data']['id'])) {
            DB::table($this->table)->delete($result['data']['id']);
        }
    }

    /**
     * Test creating record with missing required fields
     *
     * @return void
     */
    public function testCreateWithMissingFields(): void
    {
        $data = [];

        $response = $this->post('/api.php/{{MODEL}}/save', $data);

        $response->assertStatus(200)
            ->assertJson(['status' => 0]);
    }

    /**
     * Test updating record
     *
     * @return void
     */
    public function testUpdate(): void
    {
        // Create test data
        $id = DB::table($this->table)->insertGetId([
            // 'name' => 'Original Name',
            // 'status' => DBCont::NORMAL_STATUS,
        ]);

        $updateData = [
            'id' => $id,
            // 'name' => 'Updated Name',
        ];

        $response = $this->put('/api.php/{{MODEL}}/update', $updateData);

        $response->assertStatus(200)
            ->assertJson(['status' => 1]);

        // Verify update
        $updated = DB::table($this->table)->find($id);
        // $this->assertEquals('Updated Name', $updated->name);

        // Cleanup
        DB::table($this->table)->delete($id);
    }

    /**
     * Test updating non-existent record
     *
     * @return void
     */
    public function testUpdateNonExistent(): void
    {
        $updateData = [
            'id' => 999999,
            // 'name' => 'Updated Name',
        ];

        $response = $this->put('/api.php/{{MODEL}}/update', $updateData);

        $response->assertStatus(200)
            ->assertJson(['status' => 0]);
    }

    /**
     * Test deleting record
     *
     * @return void
     */
    public function testDelete(): void
    {
        // Create test data
        $id = DB::table($this->table)->insertGetId([
            // 'name' => 'To Delete',
            // 'status' => DBCont::NORMAL_STATUS,
        ]);

        $response = $this->delete('/api.php/{{MODEL}}/delete?id=' . $id);

        $response->assertStatus(200)
            ->assertJson(['status' => 1]);

        // Verify deletion
        $this->assertDatabaseMissing($this->table, ['id' => $id]);
    }

    /**
     * Test deleting non-existent record
     *
     * @return void
     */
    public function testDeleteNonExistent(): void
    {
        $response = $this->delete('/api.php/{{MODEL}}/delete?id=999999');

        $response->assertStatus(200)
            ->assertJson(['status' => 1]); // Delete returns success even if not found
    }

    /**
     * Test batch delete
     *
     * @return void
     */
    public function testBatchDelete(): void
    {
        // Create test data
        $ids = [];
        for ($i = 0; $i < 3; $i++) {
            $ids[] = DB::table($this->table)->insertGetId([
                // 'name' => 'Batch Delete Test ' . $i,
                // 'status' => DBCont::NORMAL_STATUS,
            ]);
        }

        $response = $this->post('/api.php/{{MODEL}}/batchDelete', [
            'ids' => implode(',', $ids)
        ]);

        $response->assertStatus(200)
            ->assertJson(['status' => 1]);

        // Verify deletion
        foreach ($ids as $id) {
            $this->assertDatabaseMissing($this->table, ['id' => $id]);
        }
    }

    /**
     * Test toggle status
     *
     * @return void
     */
    public function testToggleStatus(): void
    {
        // Create test data
        $id = DB::table($this->table)->insertGetId([
            // 'name' => 'Status Test',
            // 'status' => DBCont::NORMAL_STATUS,
        ]);

        // Test disable
        $response = $this->post('/api.php/{{MODEL}}/toggleStatus', [
            'id' => $id,
            'status' => DBCont::DISABLE_STATUS
        ]);

        $response->assertStatus(200)
            ->assertJson(['status' => 1]);

        // Verify status changed
        $record = DB::table($this->table)->find($id);
        $this->assertEquals(DBCont::DISABLE_STATUS, $record->status);

        // Test enable
        $response = $this->post('/api.php/{{MODEL}}/toggleStatus', [
            'id' => $id,
            'status' => DBCont::NORMAL_STATUS
        ]);

        $response->assertStatus(200)
            ->assertJson(['status' => 1]);

        // Verify status changed
        $record = DB::table($this->table)->find($id);
        $this->assertEquals(DBCont::NORMAL_STATUS, $record->status);

        // Cleanup
        DB::table($this->table)->delete($id);
    }

    /**
     * Test get options
     *
     * @return void
     */
    public function testGetOptions(): void
    {
        // Create test data
        $id = DB::table($this->table)->insertGetId([
            // 'name' => 'Option Test',
            // 'status' => DBCont::NORMAL_STATUS,
        ]);

        $response = $this->get('/api.php/{{MODEL}}/options');

        $response->assertStatus(200)
            ->assertJson(['status' => 1])
            ->assertJsonStructure([
                'status',
                'msg',
                'data' => [
                    '*' => ['value', 'label']
                ]
            ]);

        // Cleanup
        DB::table($this->table)->delete($id);
    }

    /**
     * Test with mocked external service
     *
     * @return void
     */
    public function testWithMockedApi(): void
    {
        // TODO: Create mock for external service
        // Example:
        // $mock = $this->createMock(ExternalService::class);
        // $mock->method('fetch')->willReturn(['success' => true]);
        // app()->instance(ExternalService::class, $mock);

        // $result = D('{{MODEL_NAME}}')->syncWithExternal();
        // $this->assertTrue($result);

        $this->assertTrue(true, 'Implement mock test for external services');
    }

    /**
     * Test model validation
     *
     * @return void
     */
    public function testModelValidation(): void
    {
        // Test with invalid data
        $invalidData = [
            // Add fields that should fail validation
        ];

        $result = D('{{MODEL_NAME}}')->create($invalidData);
        $this->assertFalse($result);

        // Test with valid data
        $validData = [
            // 'name' => 'Valid Name',
            // 'status' => DBCont::NORMAL_STATUS,
        ];

        $result = D('{{MODEL_NAME}}')->create($validData);
        $this->assertNotFalse($result);
    }

    /**
     * Test model methods
     *
     * @return void
     */
    public function testModelMethods(): void
    {
        // Test status list
        $statusList = D('{{MODEL_NAME}}')->getStatusList();
        $this->assertIsArray($statusList);
        $this->assertArrayHasKey(DBCont::NORMAL_STATUS, $statusList);
        $this->assertArrayHasKey(DBCont::DISABLE_STATUS, $statusList);

        // Test field options
        // $options = D('{{MODEL_NAME}}')->getFieldOptions();
        // $this->assertIsArray($options);
    }

    /**
     * Test transaction rollback
     *
     * @return void
     */
    public function testTransactionRollback(): void
    {
        // Create test data
        $id = DB::table($this->table)->insertGetId([
            // 'name' => 'Transaction Test',
            // 'status' => DBCont::NORMAL_STATUS,
        ]);

        // Start transaction
        DB::beginTransaction();

        try {
            // Update record
            DB::table($this->table)->where('id', $id)->update(['status' => DBCont::DISABLE_STATUS]);

            // Simulate error
            throw new \Exception('Test exception');

            DB::commit();
        } catch (\Exception $e) {
            DB::rollBack();
        }

        // Verify rollback
        $record = DB::table($this->table)->find($id);
        $this->assertEquals(DBCont::NORMAL_STATUS, $record->status);

        // Cleanup
        DB::table($this->table)->delete($id);
    }
}
